/* ============================================================
   CULTURE — per-country "local flavour": language, a few key
   phrases (native script + how to say it), currency, and a
   signature dish. Keyed by the country name used in the data.
   Phrases: [greeting, thank you, cheers].
   ============================================================ */
const COUNTRY_PROFILES = {
  'Albania':        { lang: 'Albanian',   currency: 'Albanian lek (L)',         dish: 'Tavë kosi — baked lamb with yogurt',
    phrases: [['Hello','Përshëndetje'],['Thank you','Faleminderit'],['Cheers','Gëzuar']] },
  'Austria':        { lang: 'German',      currency: 'Euro (€)',                 dish: 'Wiener Schnitzel & Sachertorte',
    phrases: [['Hello','Grüß Gott'],['Thank you','Danke'],['Cheers','Prost']] },
  'Belgium':        { lang: 'Dutch / French', currency: 'Euro (€)',             dish: 'Moules-frites & waffles',
    phrases: [['Hello','Hallo / Bonjour'],['Thank you','Dank u / Merci'],['Cheers','Proost / Santé']] },
  'Bosnia and Herzegovina': { lang: 'Bosnian', currency: 'Convertible mark (KM)', dish: 'Ćevapi with somun bread',
    phrases: [['Hello','Zdravo'],['Thank you','Hvala'],['Cheers','Živjeli']] },
  'Bulgaria':       { lang: 'Bulgarian',   currency: 'Bulgarian lev (лв)',       dish: 'Banitsa & shopska salad',
    phrases: [['Hello','Здравей · Zdravey'],['Thank you','Благодаря · Blagodarya'],['Cheers','Наздраве · Nazdrave']] },
  'Canada':         { lang: 'English / French', currency: 'Canadian dollar (C$)', dish: 'Poutine & butter tarts',
    phrases: [['Hello','Hello / Bonjour'],['Thank you','Thanks / Merci'],['Cheers','Cheers / Santé']] },
  'Croatia':        { lang: 'Croatian',    currency: 'Euro (€)',                 dish: 'Peka & black risotto',
    phrases: [['Hello','Bok'],['Thank you','Hvala'],['Cheers','Živjeli']] },
  'Cyprus':         { lang: 'Greek / Turkish', currency: 'Euro (€)',             dish: 'Halloumi & souvlaki',
    phrases: [['Hello','Γειά σου · Yiá sou'],['Thank you','Ευχαριστώ · Efharistó'],['Cheers','Γειά μας · Yiá mas']] },
  'Czech Republic': { lang: 'Czech',       currency: 'Czech koruna (Kč)',        dish: 'Svíčková & trdelník',
    phrases: [['Hello','Ahoj'],['Thank you','Děkuji'],['Cheers','Na zdraví']] },
  'Denmark':        { lang: 'Danish',      currency: 'Danish krone (kr)',        dish: 'Smørrebrød open sandwiches',
    phrases: [['Hello','Hej'],['Thank you','Tak'],['Cheers','Skål']] },
  'England':        { lang: 'English',     currency: 'Pound sterling (£)',       dish: 'Fish & chips, Sunday roast',
    phrases: [['Hello','Hello'],['Thank you','Thank you / Ta'],['Cheers','Cheers']] },
  'Estonia':        { lang: 'Estonian',    currency: 'Euro (€)',                 dish: 'Mulgipuder & black bread',
    phrases: [['Hello','Tere'],['Thank you','Aitäh'],['Cheers','Terviseks']] },
  'Faroe Islands':  { lang: 'Faroese',     currency: 'Danish krone (kr)',        dish: 'Ræst lamb & fresh fish',
    phrases: [['Hello','Halló'],['Thank you','Takk'],['Cheers','Skál']] },
  'Finland':        { lang: 'Finnish',     currency: 'Euro (€)',                 dish: 'Karelian pasties & salmon soup',
    phrases: [['Hello','Hei / Moi'],['Thank you','Kiitos'],['Cheers','Kippis']] },
  'France':         { lang: 'French',      currency: 'Euro (€)',                 dish: 'Croissants, coq au vin, fromage',
    phrases: [['Hello','Bonjour'],['Thank you','Merci'],['Cheers','Santé']] },
  'Germany':        { lang: 'German',      currency: 'Euro (€)',                 dish: 'Bratwurst, pretzels & beer',
    phrases: [['Hello','Hallo'],['Thank you','Danke'],['Cheers','Prost']] },
  'Greece':         { lang: 'Greek',       currency: 'Euro (€)',                 dish: 'Moussaka, souvlaki & feta',
    phrases: [['Hello','Γειά σου · Yiá sou'],['Thank you','Ευχαριστώ · Efharistó'],['Cheers','Γειά μας · Yiá mas']] },
  'Hungary':        { lang: 'Hungarian',   currency: 'Forint (Ft)',              dish: 'Goulash & chimney cake',
    phrases: [['Hello','Szia'],['Thank you','Köszönöm'],['Cheers','Egészségedre']] },
  'Iceland':        { lang: 'Icelandic',   currency: 'Icelandic króna (kr)',     dish: 'Plokkfiskur & lamb soup',
    phrases: [['Hello','Halló'],['Thank you','Takk'],['Cheers','Skál']] },
  'Ireland':        { lang: 'Irish / English', currency: 'Euro (€)',             dish: 'Irish stew & soda bread',
    phrases: [['Hello','Dia duit'],['Thank you','Go raibh maith agat'],['Cheers','Sláinte']] },
  'Italy':          { lang: 'Italian',     currency: 'Euro (€)',                 dish: 'Pasta, pizza & gelato',
    phrases: [['Hello','Ciao'],['Thank you','Grazie'],['Cheers','Salute / Cin cin']] },
  'Malta':          { lang: 'Maltese',     currency: 'Euro (€)',                 dish: 'Fenkata (rabbit stew) & pastizzi',
    phrases: [['Hello','Bonġu'],['Thank you','Grazzi'],['Cheers','Saħħa']] },
  'Montenegro':     { lang: 'Montenegrin', currency: 'Euro (€)',                 dish: 'Njeguški pršut & kačamak',
    phrases: [['Hello','Zdravo'],['Thank you','Hvala'],['Cheers','Živjeli']] },
  'Netherlands':    { lang: 'Dutch',       currency: 'Euro (€)',                 dish: 'Stroopwafels & haring',
    phrases: [['Hello','Hallo'],['Thank you','Dank je'],['Cheers','Proost']] },
  'Norway':         { lang: 'Norwegian',   currency: 'Norwegian krone (kr)',     dish: 'Fårikål & brown cheese',
    phrases: [['Hello','Hei'],['Thank you','Takk'],['Cheers','Skål']] },
  'Poland':         { lang: 'Polish',      currency: 'Złoty (zł)',               dish: 'Pierogi & żurek soup',
    phrases: [['Hello','Cześć'],['Thank you','Dziękuję'],['Cheers','Na zdrowie']] },
  'Portugal':       { lang: 'Portuguese',  currency: 'Euro (€)',                 dish: 'Bacalhau & pastéis de nata',
    phrases: [['Hello','Olá'],['Thank you','Obrigado/a'],['Cheers','Saúde']] },
  'Romania':        { lang: 'Romanian',    currency: 'Romanian leu (lei)',       dish: 'Sarmale & mămăligă',
    phrases: [['Hello','Bună'],['Thank you','Mulțumesc'],['Cheers','Noroc']] },
  'Spain':          { lang: 'Spanish',     currency: 'Euro (€)',                 dish: 'Paella, tapas & jamón',
    phrases: [['Hello','Hola'],['Thank you','Gracias'],['Cheers','Salud']] },
  'Sweden':         { lang: 'Swedish',     currency: 'Swedish krona (kr)',       dish: 'Köttbullar & cinnamon buns',
    phrases: [['Hello','Hej'],['Thank you','Tack'],['Cheers','Skål']] },
  'Switzerland':    { lang: 'German / French / Italian', currency: 'Swiss franc (CHF)', dish: 'Fondue, raclette & rösti',
    phrases: [['Hello','Grüezi / Bonjour'],['Thank you','Danke / Merci'],['Cheers','Prost / Santé']] },
  'Turkey':         { lang: 'Turkish',     currency: 'Turkish lira (₺)',         dish: 'Kebabs, meze & baklava',
    phrases: [['Hello','Merhaba'],['Thank you','Teşekkürler'],['Cheers','Şerefe']] },
  'United Kingdom': { lang: 'English',     currency: 'Pound sterling (£)',       dish: 'Fish & chips, Sunday roast',
    phrases: [['Hello','Hello'],['Thank you','Thank you / Ta'],['Cheers','Cheers']] },
  'United States':  { lang: 'English',     currency: 'US dollar ($)',            dish: 'Burgers, BBQ & apple pie',
    phrases: [['Hello','Hello / Hi'],['Thank you','Thank you'],['Cheers','Cheers']] },
  'Mexico':         { lang: 'Spanish',     currency: 'Mexican peso ($/MXN)',     dish: 'Tacos al pastor & mole',
    phrases: [['Hello','Hola'],['Thank you','Gracias'],['Cheers','Salud']] },
  'Indonesia':      { lang: 'Indonesian',  currency: 'Indonesian rupiah (Rp)',   dish: 'Nasi goreng & satay',
    phrases: [['Hello','Halo'],['Thank you','Terima kasih'],['Cheers','Bersulang']] },
  'Micronesia':     { lang: 'English / Pohnpeian', currency: 'US dollar ($)',    dish: 'Reef fish, taro & breadfruit',
    phrases: [['Hello','Kaselehlie'],['Thank you','Kalahngan'],['Cheers','Cheers']] },
  'Bahamas':        { lang: 'English',     currency: 'Bahamian dollar (B$)',     dish: 'Conch fritters & rock lobster',
    phrases: [['Hello','Hello'],['Thank you','Thank you'],['Cheers','Cheers']] },
  'Brazil':         { lang: 'Portuguese',  currency: 'Brazilian real (R$)',      dish: 'Feijoada & pão de queijo',
    phrases: [['Hello','Olá'],['Thank you','Obrigado/a'],['Cheers','Saúde']] },
  'Chile':          { lang: 'Spanish',     currency: 'Chilean peso ($/CLP)',     dish: 'Empanadas & pastel de choclo',
    phrases: [['Hello','Hola'],['Thank you','Gracias'],['Cheers','Salud']] },
  'Peru':           { lang: 'Spanish / Quechua', currency: 'Peruvian sol (S/)',  dish: 'Ceviche & lomo saltado',
    phrases: [['Hello','Hola'],['Thank you','Gracias'],['Cheers','Salud']] },
  /* === world-expansion countries (build_culture.py) — review phrases/dishes === */
  'Japan': { lang: 'Japanese', currency: 'Japanese yen (¥)', dish: 'Sushi, ramen & tempura', phrases: [['Hello','こんにちは'],['Thank you','ありがとう'],['Cheers','乾杯 (Kanpai)']] },
  'China': { lang: 'Mandarin Chinese', currency: 'Chinese yuan (¥)', dish: 'Peking duck & dim sum', phrases: [['Hello','你好 (Nǐ hǎo)'],['Thank you','谢谢 (Xièxie)'],['Cheers','干杯 (Gānbēi)']] },
  'India': { lang: 'Hindi / English', currency: 'Indian rupee (₹)', dish: 'Curry, biryani & dosa', phrases: [['Hello','नमस्ते (Namaste)'],['Thank you','धन्यवाद (Dhanyavaad)'],['Cheers','Cheers']] },
  'South Korea': { lang: 'Korean', currency: 'South Korean won (₩)', dish: 'Kimchi & Korean BBQ', phrases: [['Hello','안녕하세요 (Annyeong)'],['Thank you','감사합니다 (Gamsahamnida)'],['Cheers','건배 (Geonbae)']] },
  'Thailand': { lang: 'Thai', currency: 'Thai baht (฿)', dish: 'Pad Thai & green curry', phrases: [['Hello','สวัสดี (Sawasdee)'],['Thank you','ขอบคุณ (Khop khun)'],['Cheers','ไชโย (Chai-yo)']] },
  'Malaysia': { lang: 'Malay', currency: 'Malaysian ringgit (RM)', dish: 'Nasi lemak & laksa', phrases: [['Hello','Selamat'],['Thank you','Terima kasih'],['Cheers','Cheers']] },
  'Singapore': { lang: 'English / Malay / Mandarin / Tamil', currency: 'Singapore dollar (S$)', dish: 'Chicken rice & chilli crab', phrases: [['Hello','Hello'],['Thank you','Thank you / Terima kasih'],['Cheers','Cheers / Yum seng']] },
  'Philippines': { lang: 'Filipino / English', currency: 'Philippine peso (₱)', dish: 'Adobo & lechon', phrases: [['Hello','Kumusta'],['Thank you','Salamat'],['Cheers','Tagay']] },
  'Vietnam': { lang: 'Vietnamese', currency: 'Vietnamese đồng (₫)', dish: 'Phở & bánh mì', phrases: [['Hello','Xin chào'],['Thank you','Cảm ơn'],['Cheers','Dô / Một hai ba dô']] },
  'Cambodia': { lang: 'Khmer', currency: 'Cambodian riel (៛)', dish: 'Fish amok & lok lak', phrases: [['Hello','Suosdey'],['Thank you','Aw kun'],['Cheers','Chol mouy']] },
  'Laos': { lang: 'Lao', currency: 'Lao kip (₭)', dish: 'Larb & sticky rice', phrases: [['Hello','Sabaidee'],['Thank you','Khob chai'],['Cheers','Sok dee']] },
  'Taiwan': { lang: 'Mandarin Chinese', currency: 'New Taiwan dollar (NT$)', dish: 'Beef noodle soup & bubble tea', phrases: [['Hello','你好 (Nǐ hǎo)'],['Thank you','謝謝 (Xièxie)'],['Cheers','乾杯 (Gānbēi)']] },
  'Mongolia': { lang: 'Mongolian', currency: 'Mongolian tögrög (₮)', dish: 'Buuz dumplings & khorkhog', phrases: [['Hello','Sain baina uu'],['Thank you','Bayarlalaa'],['Cheers','Tuluunii toloo']] },
  'Sri Lanka': { lang: 'Sinhala / Tamil', currency: 'Sri Lankan rupee (Rs)', dish: 'Rice & curry, hoppers', phrases: [['Hello','Ayubowan'],['Thank you','Sthuthi'],['Cheers','Cheers']] },
  'Israel': { lang: 'Hebrew', currency: 'Israeli shekel (₪)', dish: 'Hummus, falafel & shakshuka', phrases: [['Hello','שלום (Shalom)'],['Thank you','תודה (Toda)'],['Cheers','לחיים (L\'chaim)']] },
  'United Arab Emirates': { lang: 'Arabic', currency: 'UAE dirham (د.إ)', dish: 'Shawarma & machboos', phrases: [['Hello','مرحبا (Marhaba)'],['Thank you','شكرا (Shukran)'],['Cheers','بصحتك (Bisaha)']] },
  'Saudi Arabia': { lang: 'Arabic', currency: 'Saudi riyal (ر.س)', dish: 'Kabsa & shawarma', phrases: [['Hello','مرحبا (Marhaba)'],['Thank you','شكرا (Shukran)'],['Cheers','بصحتك (Bisaha)']] },
  'Qatar': { lang: 'Arabic', currency: 'Qatari riyal (ر.ق)', dish: 'Machboos & balaleet', phrases: [['Hello','مرحبا (Marhaba)'],['Thank you','شكرا (Shukran)'],['Cheers','بصحتك (Bisaha)']] },
  'Jordan': { lang: 'Arabic', currency: 'Jordanian dinar (د.ا)', dish: 'Mansaf & falafel', phrases: [['Hello','مرحبا (Marhaba)'],['Thank you','شكرا (Shukran)'],['Cheers','بصحتك (Bisaha)']] },
  'Iran': { lang: 'Persian (Farsi)', currency: 'Iranian rial (﷼)', dish: 'Kebab & ghormeh sabzi', phrases: [['Hello','سلام (Salam)'],['Thank you','ممنون (Mamnoon)'],['Cheers','به سلامتی (Be salamati)']] },
  'Armenia': { lang: 'Armenian', currency: 'Armenian dram (֏)', dish: 'Khorovats & dolma', phrases: [['Hello','Բարև (Barev)'],['Thank you','Շնորհակալություն (Shnorhakalutyun)'],['Cheers','Կենաց (Kenats)']] },
  'Azerbaijan': { lang: 'Azerbaijani', currency: 'Azerbaijani manat (₼)', dish: 'Plov & dolma', phrases: [['Hello','Salam'],['Thank you','Təşəkkür'],['Cheers','Nuş olsun']] },
  'Georgia': { lang: 'Georgian', currency: 'Georgian lari (₾)', dish: 'Khachapuri & khinkali', phrases: [['Hello','გამარჯობა (Gamarjoba)'],['Thank you','მადლობა (Madloba)'],['Cheers','გაუმარჯოს (Gaumarjos)']] },
  'North Korea': { lang: 'Korean', currency: 'North Korean won (₩)', dish: 'Pyongyang naengmyŏn (cold noodles)', phrases: [['Hello','안녕하십니까 (Annyŏng hasimnikka)'],['Thank you','감사합니다 (Kamsahamnida)'],['Cheers','축배 (Chukbae)']] },
  'Morocco': { lang: 'Arabic / Berber', currency: 'Moroccan dirham (د.م.)', dish: 'Tagine & couscous', phrases: [['Hello','السلام (Salam)'],['Thank you','شكرا (Shukran)'],['Cheers','بصحتك (Bsaha)']] },
  'Egypt': { lang: 'Arabic', currency: 'Egyptian pound (£)', dish: 'Koshari & ful medames', phrases: [['Hello','السلام عليكم (Salam)'],['Thank you','شكرا (Shukran)'],['Cheers','في صحتك (Fi sahetak)']] },
  'Kenya': { lang: 'Swahili / English', currency: 'Kenyan shilling (KSh)', dish: 'Nyama choma & ugali', phrases: [['Hello','Jambo'],['Thank you','Asante'],['Cheers','Maisha marefu']] },
  'Senegal': { lang: 'French / Wolof', currency: 'West African CFA franc (CFA)', dish: 'Thieboudienne', phrases: [['Hello','Bonjour / Salaam'],['Thank you','Merci / Jërëjëf'],['Cheers','Santé']] },
  'Ethiopia': { lang: 'Amharic', currency: 'Ethiopian birr (Br)', dish: 'Injera & doro wat', phrases: [['Hello','ሰላም (Selam)'],['Thank you','አመሰግናለሁ (Ameseginalehu)'],['Cheers','Bechewanet']] },
  'Gambia': { lang: 'English', currency: 'Gambian dalasi (D)', dish: 'Domoda & benachin', phrases: [['Hello','Hello / Salaam'],['Thank you','Thank you / Jërejëf'],['Cheers','Cheers']] },
  'South Africa': { lang: 'English / Zulu / Afrikaans', currency: 'South African rand (R)', dish: 'Braai & bobotie', phrases: [['Hello','Hello / Sawubona'],['Thank you','Thank you / Ngiyabonga'],['Cheers','Cheers']] },
  'Namibia': { lang: 'English / Oshiwambo / Afrikaans', currency: 'Namibian dollar (N$)', dish: 'Kapana & game biltong', phrases: [['Hello','Hello / Wa lalapo'],['Thank you','Thank you / Tangi'],['Cheers','Cheers']] },
  'Zimbabwe': { lang: 'Shona / Ndebele / English', currency: 'Zimbabwe gold (ZiG) & US dollar', dish: 'Sadza & nyama', phrases: [['Hello','Mhoro'],['Thank you','Ndatenda'],['Cheers','Cheers']] },
  'DR Congo': { lang: 'French / Lingala / Swahili', currency: 'Congolese franc (FC)', dish: 'Fufu & pondu', phrases: [['Hello','Mbote'],['Thank you','Matondo'],['Cheers','Santé']] },
  'Tunisia': { lang: 'Arabic / French', currency: 'Tunisian dinar (د.ت)', dish: 'Couscous & brik', phrases: [['Hello','السلام (Salam)'],['Thank you','شكرا (Shukran)'],['Cheers','بصحتك (Bsahtek)']] },
  'Algeria': { lang: 'Arabic / Berber / French', currency: 'Algerian dinar (د.ج)', dish: 'Couscous & chorba', phrases: [['Hello','السلام (Salam)'],['Thank you','شكرا (Shukran)'],['Cheers','بصحتك (Bsahtek)']] },
  'Libya': { lang: 'Arabic', currency: 'Libyan dinar (ل.د)', dish: 'Bazin & couscous', phrases: [['Hello','السلام (Salam)'],['Thank you','شكرا (Shukran)'],['Cheers','في صحتك (Fi sahetak)']] },
  'Sudan': { lang: 'Arabic / English', currency: 'Sudanese pound (ج.س)', dish: 'Ful medames & kisra', phrases: [['Hello','السلام عليكم (Salam)'],['Thank you','شكرا (Shukran)'],['Cheers','في صحتك (Fi sahetak)']] },
  'South Sudan': { lang: 'English / Arabic', currency: 'South Sudanese pound (£)', dish: 'Kisra & asida', phrases: [['Hello','Hello / Salam'],['Thank you','Thank you / Shukran'],['Cheers','Cheers']] },
  'Mauritania': { lang: 'Arabic / French', currency: 'Mauritanian ouguiya (UM)', dish: 'Thieboudienne & mechoui', phrases: [['Hello','السلام (Salam)'],['Thank you','شكرا (Shukran)'],['Cheers','بصحتك (Bsaha)']] },
  'Mali': { lang: 'French / Bambara', currency: 'West African CFA franc (CFA)', dish: 'Tigadèguèna — peanut stew', phrases: [['Hello','Bonjour / I ni ce'],['Thank you','Merci / I ni ce'],['Cheers','Santé']] },
  'Niger': { lang: 'French / Hausa', currency: 'West African CFA franc (CFA)', dish: 'Dambou & brochettes', phrases: [['Hello','Bonjour / Sannu'],['Thank you','Merci / Na gode'],['Cheers','Santé']] },
  'Chad': { lang: 'French / Arabic', currency: 'Central African CFA franc (FCFA)', dish: 'Boule & daraba', phrases: [['Hello','Bonjour / Salam'],['Thank you','Merci / Shukran'],['Cheers','Santé']] },
  'Burkina Faso': { lang: 'French / Mooré', currency: 'West African CFA franc (CFA)', dish: 'Riz gras & tô', phrases: [['Hello','Bonjour / Ne y windga'],['Thank you','Merci / Barka'],['Cheers','Santé']] },
  'Nigeria': { lang: 'English / Hausa / Yoruba / Igbo', currency: 'Nigerian naira (₦)', dish: 'Jollof rice & suya', phrases: [['Hello','Hello / Sannu'],['Thank you','Thank you / Na gode'],['Cheers','Cheers']] },
  'Ghana': { lang: 'English / Twi', currency: 'Ghanaian cedi (₵)', dish: 'Jollof, waakye & banku', phrases: [['Hello','Hello / Ɛte sɛn'],['Thank you','Medaase'],['Cheers','Cheers']] },
  'Togo': { lang: 'French / Ewé', currency: 'West African CFA franc (CFA)', dish: 'Fufu & akpan', phrases: [['Hello','Bonjour / Woezon'],['Thank you','Merci / Akpé'],['Cheers','Santé']] },
  'Benin': { lang: 'French / Fon', currency: 'West African CFA franc (CFA)', dish: 'Amiwo & akassa', phrases: [['Hello','Bonjour / Kudo'],['Thank you','Merci / Awanou'],['Cheers','Santé']] },
  'Côte d\'Ivoire': { lang: 'French', currency: 'West African CFA franc (CFA)', dish: 'Attiéké & kedjenou', phrases: [['Hello','Bonjour'],['Thank you','Merci'],['Cheers','Santé']] },
  'Guinea': { lang: 'French / Susu / Fula', currency: 'Guinean franc (FG)', dish: 'Riz gras & poulet yassa', phrases: [['Hello','Bonjour / Tana muxu'],['Thank you','Merci'],['Cheers','Santé']] },
  'Guinea-Bissau': { lang: 'Portuguese / Creole', currency: 'West African CFA franc (CFA)', dish: 'Caldo de mancarra', phrases: [['Hello','Olá / Kuma ku bai'],['Thank you','Obrigado'],['Cheers','Saúde']] },
  'Sierra Leone': { lang: 'English / Krio', currency: 'Sierra Leonean leone (Le)', dish: 'Cassava leaves & jollof', phrases: [['Hello','Hello / Kushɛ'],['Thank you','Tenki'],['Cheers','Cheers']] },
  'Liberia': { lang: 'English', currency: 'Liberian dollar (L$)', dish: 'Jollof rice & palm butter', phrases: [['Hello','Hello'],['Thank you','Thank you'],['Cheers','Cheers']] },
  'Cape Verde': { lang: 'Portuguese / Creole', currency: 'Cape Verdean escudo ($)', dish: 'Cachupa', phrases: [['Hello','Olá / Oi'],['Thank you','Obrigado'],['Cheers','Saúde']] },
  'Cameroon': { lang: 'French / English', currency: 'Central African CFA franc (FCFA)', dish: 'Ndolé & poulet DG', phrases: [['Hello','Bonjour / Hello'],['Thank you','Merci / Thank you'],['Cheers','Santé']] },
  'Gabon': { lang: 'French', currency: 'Central African CFA franc (FCFA)', dish: 'Poulet nyembwe', phrases: [['Hello','Bonjour'],['Thank you','Merci'],['Cheers','Santé']] },
  'Republic of the Congo': { lang: 'French / Lingala / Kituba', currency: 'Central African CFA franc (FCFA)', dish: 'Saka-saka & poulet moambé', phrases: [['Hello','Bonjour / Mbote'],['Thank you','Merci / Matondo'],['Cheers','Santé']] },
  'Central African Republic': { lang: 'Sango / French', currency: 'Central African CFA franc (FCFA)', dish: 'Kanda ti nyma & gozo', phrases: [['Hello','Bara ala'],['Thank you','Singila'],['Cheers','Santé']] },
  'Equatorial Guinea': { lang: 'Spanish / French / Portuguese', currency: 'Central African CFA franc (FCFA)', dish: 'Succotash & pepesup', phrases: [['Hello','Hola'],['Thank you','Gracias'],['Cheers','Salud']] },
  'São Tomé and Príncipe': { lang: 'Portuguese', currency: 'São Tomé dobra (Db)', dish: 'Calulu & banana bread', phrases: [['Hello','Olá'],['Thank you','Obrigado'],['Cheers','Saúde']] },
  'Angola': { lang: 'Portuguese', currency: 'Angolan kwanza (Kz)', dish: 'Funge & muamba de galinha', phrases: [['Hello','Olá'],['Thank you','Obrigado'],['Cheers','Saúde']] },
  'Uganda': { lang: 'English / Swahili / Luganda', currency: 'Ugandan shilling (USh)', dish: 'Matoke & the rolex', phrases: [['Hello','Oli otya'],['Thank you','Webale'],['Cheers','Cheers']] },
  'Rwanda': { lang: 'Kinyarwanda / English / French', currency: 'Rwandan franc (FRw)', dish: 'Isombe & brochettes', phrases: [['Hello','Muraho'],['Thank you','Murakoze'],['Cheers','Cheers']] },
  'Burundi': { lang: 'Kirundi / French', currency: 'Burundian franc (FBu)', dish: 'Boko boko & red beans', phrases: [['Hello','Amahoro'],['Thank you','Urakoze'],['Cheers','Santé']] },
  'Tanzania': { lang: 'Swahili / English', currency: 'Tanzanian shilling (TSh)', dish: 'Ugali & nyama choma', phrases: [['Hello','Jambo / Habari'],['Thank you','Asante'],['Cheers','Afya']] },
  'Eritrea': { lang: 'Tigrinya / Arabic / English', currency: 'Eritrean nakfa (Nfk)', dish: 'Injera & zigni', phrases: [['Hello','ሰላም (Selam)'],['Thank you','የቐንየለይ (Yekenyeley)'],['Cheers','Cheers']] },
  'Djibouti': { lang: 'French / Arabic', currency: 'Djiboutian franc (Fdj)', dish: 'Skoudehkaris', phrases: [['Hello','Bonjour / Salam'],['Thank you','Merci / Shukran'],['Cheers','Santé']] },
  'Somalia': { lang: 'Somali / Arabic', currency: 'Somali shilling (Sh)', dish: 'Bariis iskukaris & suqaar', phrases: [['Hello','Iska warran'],['Thank you','Mahadsanid'],['Cheers','Cheers']] },
  'Madagascar': { lang: 'Malagasy / French', currency: 'Malagasy ariary (Ar)', dish: 'Romazava & ravitoto', phrases: [['Hello','Salama'],['Thank you','Misaotra'],['Cheers','Santé']] },
  'Mauritius': { lang: 'English / French / Creole', currency: 'Mauritian rupee (₨)', dish: 'Dholl puri & rougaille', phrases: [['Hello','Bonzour'],['Thank you','Mersi'],['Cheers','Santé']] },
  'Seychelles': { lang: 'Creole / English / French', currency: 'Seychellois rupee (₨)', dish: 'Grilled fish & octopus curry', phrases: [['Hello','Bonzour'],['Thank you','Mersi'],['Cheers','Santé']] },
  'Comoros': { lang: 'Comorian / Arabic / French', currency: 'Comorian franc (CF)', dish: 'Langouste à la vanille', phrases: [['Hello','Bariza'],['Thank you','Marahaba'],['Cheers','Santé']] },
  'Malawi': { lang: 'Chichewa / English', currency: 'Malawian kwacha (MK)', dish: 'Nsima & chambo', phrases: [['Hello','Moni'],['Thank you','Zikomo'],['Cheers','Cheers']] },
  'Mozambique': { lang: 'Portuguese', currency: 'Mozambican metical (MT)', dish: 'Peri-peri prawns & matapa', phrases: [['Hello','Olá'],['Thank you','Obrigado'],['Cheers','Saúde']] },
  'Zambia': { lang: 'English / Bemba / Nyanja', currency: 'Zambian kwacha (K)', dish: 'Nshima & kapenta', phrases: [['Hello','Muli bwanji'],['Thank you','Zikomo'],['Cheers','Cheers']] },
  'Botswana': { lang: 'Setswana / English', currency: 'Botswana pula (P)', dish: 'Seswaa & bogobe', phrases: [['Hello','Dumela'],['Thank you','Ke a leboga'],['Cheers','Cheers']] },
  'Lesotho': { lang: 'Sesotho / English', currency: 'Lesotho loti (L)', dish: 'Papa & moroho', phrases: [['Hello','Lumela'],['Thank you','Kea leboha'],['Cheers','Cheers']] },
  'Eswatini': { lang: 'siSwati / English', currency: 'Swazi lilangeni (L)', dish: 'Sishwala & emasi', phrases: [['Hello','Sawubona'],['Thank you','Ngiyabonga'],['Cheers','Cheers']] },
  'Australia': { lang: 'English', currency: 'Australian dollar (A$)', dish: 'Meat pie, barramundi & Vegemite', phrases: [['Hello','G\'day'],['Thank you','Thanks / Ta'],['Cheers','Cheers']] },
  'New Zealand': { lang: 'English / Māori', currency: 'New Zealand dollar (NZ$)', dish: 'Hāngī & pavlova', phrases: [['Hello','Kia ora'],['Thank you','Ngā mihi'],['Cheers','Cheers']] },
  'Papua New Guinea': { lang: 'Tok Pisin / English / Hiri Motu', currency: 'Papua New Guinean kina (K)', dish: 'Mumu — pork, kaukau & greens in an earth oven', phrases: [['Hello','Gude'],['Thank you','Tenkyu tru'],['Cheers','Amamas']] },
  'Fiji': { lang: 'Fijian / English / Fiji Hindi', currency: 'Fijian dollar (FJ$)', dish: 'Kokoda — lime-cured fish in coconut milk', phrases: [['Hello','Bula'],['Thank you','Vinaka'],['Cheers','Bula!']] },
  'Solomon Islands': { lang: 'English / Solomons Pijin', currency: 'Solomon Islands dollar (SI$)', dish: 'Fish in coconut milk with poi', phrases: [['Hello','Halo'],['Thank you','Tagio tumas'],['Cheers','Cheers']] },
  'Vanuatu': { lang: 'Bislama / English / French', currency: 'Vanuatu vatu (VT)', dish: 'Laplap — grated root baked in banana leaf', phrases: [['Hello','Halo'],['Thank you','Tankiu tumas'],['Cheers','Cheers']] },
  'New Caledonia': { lang: 'French / 28 Kanak languages', currency: 'CFP franc (₣)', dish: 'Bougna — yam, taro & coconut milk baked in leaves', phrases: [['Hello','Bonjour'],['Thank you','Merci'],['Cheers','Santé']] },
  'Samoa': { lang: 'Samoan / English', currency: 'Samoan tālā (T$)', dish: 'Palusami & oka — taro leaves and raw fish in coconut cream', phrases: [['Hello','Tālofa'],['Thank you','Fa\'afetai'],['Cheers','Manuia']] },
  'American Samoa': { lang: 'Samoan / English', currency: 'US dollar ($)', dish: 'Palusami & povi masima', phrases: [['Hello','Tālofa'],['Thank you','Fa\'afetai'],['Cheers','Manuia']] },
  'Tonga': { lang: 'Tongan / English', currency: 'Tongan paʻanga (T$)', dish: 'ʻOta ʻika & lū pulu', phrases: [['Hello','Mālō e lelei'],['Thank you','Mālō ʻaupito'],['Cheers','Mālō']] },
  'Cook Islands': { lang: 'Cook Islands Māori / English', currency: 'New Zealand dollar (NZ$)', dish: 'Ika mata — raw fish in coconut cream', phrases: [['Hello','Kia orana'],['Thank you','Meitaki'],['Cheers','Kia manuia']] },
  'French Polynesia': { lang: 'French / Tahitian', currency: 'CFP franc (₣)', dish: 'Poisson cru (ʻia ota) & poe', phrases: [['Hello','Ia ora na'],['Thank you','Māuruuru'],['Cheers','Manuia']] },
  'Niue': { lang: 'Niuean / English', currency: 'New Zealand dollar (NZ$)', dish: 'Takihi — pawpaw and taro baked in coconut cream', phrases: [['Hello','Fakalofa lahi atu'],['Thank you','Fakaaue lahi'],['Cheers','Kia monuina']] },
  'Kiribati': { lang: 'Gilbertese / English', currency: 'Australian dollar (A$)', dish: 'Coconut-braised reef fish & breadfruit', phrases: [['Hello','Mauri'],['Thank you','Ko rabwa'],['Cheers','Mauri']] },
  'Tuvalu': { lang: 'Tuvaluan / English', currency: 'Australian dollar (A$)', dish: 'Pulaka & coconut-poached fish', phrases: [['Hello','Tālofa'],['Thank you','Fakafetai'],['Cheers','Manuia']] },
  'Nauru': { lang: 'Nauruan / English', currency: 'Australian dollar (A$)', dish: 'Coconut fish & pandanus', phrases: [['Hello','Ekamowir omo'],['Thank you','Tubwa kor'],['Cheers','Cheers']] },
  'Palau': { lang: 'Palauan / English', currency: 'US dollar ($)', dish: 'Taro, reef fish & tinola', phrases: [['Hello','Alii'],['Thank you','Sulang'],['Cheers','Alii']] },
  'Marshall Islands': { lang: 'Marshallese / English', currency: 'US dollar ($)', dish: 'Breadfruit, reef fish & coconut', phrases: [['Hello','Iakwe'],['Thank you','Kommol tata'],['Cheers','Iakwe']] },
  'Guam': { lang: 'English / CHamoru', currency: 'US dollar ($)', dish: 'Kelaguen & red rice', phrases: [['Hello','Håfa adai'],['Thank you','Si Yu\'os ma\'åse\''],['Cheers','Biba!']] },
  'Northern Mariana Islands': { lang: 'English / CHamoru / Carolinian', currency: 'US dollar ($)', dish: 'Kelaguen & apigigi', phrases: [['Hello','Håfa adai'],['Thank you','Si Yu\'os ma\'åse\''],['Cheers','Biba!']] },
  'Norfolk Island': { lang: 'English / Norf\'k', currency: 'Australian dollar (A$)', dish: 'Pilhi — banana or pumpkin baked flat', phrases: [['Hello','Watawieh'],['Thank you','Thank yorlye'],['Cheers','Cheers']] },
  'Pitcairn Islands': { lang: 'English / Pitkern', currency: 'New Zealand dollar (NZ$)', dish: 'Pilhi & breadfruit', phrases: [['Hello','Whata way ye'],['Thank you','Thank ye'],['Cheers','Cheers']] },
  'Argentina': { lang: 'Spanish', currency: 'Argentine peso ($)', dish: 'Asado & empanadas', phrases: [['Hello','Hola'],['Thank you','Gracias'],['Cheers','Salud']] },
  'Bolivia': { lang: 'Spanish / Quechua / Aymara', currency: 'Bolivian boliviano (Bs)', dish: 'Salteñas & silpancho', phrases: [['Hello','Hola'],['Thank you','Gracias'],['Cheers','Salud']] },
  'Colombia': { lang: 'Spanish', currency: 'Colombian peso ($)', dish: 'Bandeja paisa & arepas', phrases: [['Hello','Hola'],['Thank you','Gracias'],['Cheers','Salud']] },
  'Uruguay': { lang: 'Spanish', currency: 'Uruguayan peso ($U)', dish: 'Asado & chivito', phrases: [['Hello','Hola'],['Thank you','Gracias'],['Cheers','Salud']] },
  'Paraguay': { lang: 'Spanish / Guaraní', currency: 'Paraguayan guaraní (₲)', dish: 'Sopa paraguaya & chipá', phrases: [['Hello','Mba\'éichapa'],['Thank you','Aguyje'],['Cheers','Salud']] },
  'Cuba': { lang: 'Spanish', currency: 'Cuban peso ($)', dish: 'Ropa vieja & moros y cristianos', phrases: [['Hello','Hola'],['Thank you','Gracias'],['Cheers','Salud']] },
  'Costa Rica': { lang: 'Spanish', currency: 'Costa Rican colón (₡)', dish: 'Gallo pinto & casado', phrases: [['Hello','Hola / Pura vida'],['Thank you','Gracias'],['Cheers','Salud']] },
  'Belize': { lang: 'English / Kriol', currency: 'Belize dollar (BZ$)', dish: 'Rice & beans, stew chicken', phrases: [['Hello','Hello'],['Thank you','Thank you'],['Cheers','Cheers']] },
  'Ukraine': { lang: 'Ukrainian', currency: 'Ukrainian hryvnia (₴)', dish: 'Borscht & varenyky', phrases: [['Hello','Привіт (Pryvit)'],['Thank you','Дякую (Diakuyu)'],['Cheers','Будьмо (Budmo)']] },
  'Serbia': { lang: 'Serbian', currency: 'Serbian dinar (дин)', dish: 'Ćevapi & pljeskavica', phrases: [['Hello','Здраво (Zdravo)'],['Thank you','Хвала (Hvala)'],['Cheers','Живели (Živeli)']] },
  'Luxembourg': { lang: 'Luxembourgish / French / German', currency: 'Euro (€)', dish: 'Judd mat Gaardebounen', phrases: [['Hello','Moien'],['Thank you','Merci'],['Cheers','Prost / Santé']] },
  'Lithuania': { lang: 'Lithuanian', currency: 'Euro (€)', dish: 'Cepelinai & šaltibarščiai', phrases: [['Hello','Labas'],['Thank you','Ačiū'],['Cheers','Į sveikatą']] },
  'Latvia': { lang: 'Latvian', currency: 'Euro (€)', dish: 'Grey peas & speck', phrases: [['Hello','Sveiki'],['Thank you','Paldies'],['Cheers','Priekā']] },
  'Moldova': { lang: 'Romanian', currency: 'Moldovan leu (L)', dish: 'Mămăligă & sarmale', phrases: [['Hello','Bună'],['Thank you','Mulțumesc'],['Cheers','Noroc']] },
  'Slovakia': { lang: 'Slovak', currency: 'Euro (€)', dish: 'Bryndzové halušky', phrases: [['Hello','Ahoj'],['Thank you','Ďakujem'],['Cheers','Na zdravie']] },
  'Slovenia': { lang: 'Slovene', currency: 'Euro (€)', dish: 'Potica & štruklji', phrases: [['Hello','Živjo'],['Thank you','Hvala'],['Cheers','Na zdravje']] },
  'Vatican City': { lang: 'Italian / Latin', currency: 'Euro (€)', dish: 'Roman pasta — cacio e pepe', phrases: [['Hello','Buongiorno'],['Thank you','Grazie'],['Cheers','Salute']] },
  'Russia': { lang: 'Russian', currency: 'Russian ruble (₽)', dish: 'Borscht, pelmeni & blini', phrases: [['Hello','Привет (Privet)'],['Thank you','Спасибо (Spasibo)'],['Cheers','На здоровье (Na zdorovie)']] },
  'Belarus': { lang: 'Belarusian / Russian', currency: 'Belarusian ruble (Br)', dish: 'Draniki & machanka', phrases: [['Hello','Прывітанне (Pryvitannie)'],['Thank you','Дзякуй (Dziakuj)'],['Cheers','Будзьма (Budzma)']] },
  'Brunei': { lang: 'Malay', currency: 'Brunei dollar (B$)', dish: 'Ambuyat & nasi katok', phrases: [['Hello','Salam'],['Thank you','Terima kasih'],['Cheers','Cheers']] },
  'Myanmar': { lang: 'Burmese', currency: 'Myanmar kyat (K)', dish: 'Mohinga & tea leaf salad', phrases: [['Hello','မင်္ဂလာပါ (Mingalaba)'],['Thank you','ကျေးဇူးတင်ပါတယ် (Kyay zu tin ba de)'],['Cheers','Aung myin par say']] },
  'Kazakhstan': { lang: 'Kazakh / Russian', currency: 'Kazakhstani tenge (₸)', dish: 'Beshbarmak & baursak', phrases: [['Hello','Сәлеметсіз бе (Sälemetsiz be)'],['Thank you','Рахмет (Rakhmet)'],['Cheers','Сау болыңыз (Sau bolyñyz)']] },
  'Uzbekistan': { lang: 'Uzbek / Russian', currency: 'Uzbekistani so\'m (so\'m)', dish: 'Plov & samsa', phrases: [['Hello','Salom'],['Thank you','Rahmat'],['Cheers','Olqishlar']] },
  'Kyrgyzstan': { lang: 'Kyrgyz / Russian', currency: 'Kyrgyzstani som (с)', dish: 'Beshbarmak & laghman', phrases: [['Hello','Салам (Salam)'],['Thank you','Рахмат (Rakhmat)'],['Cheers','Den sooluk']] },
  'Tajikistan': { lang: 'Tajik / Russian', currency: 'Tajikistani somoni (SM)', dish: 'Qurutob & plov', phrases: [['Hello','Салом (Salom)'],['Thank you','Раҳмат (Rahmat)'],['Cheers','Ba salomati']] },
  'Turkmenistan': { lang: 'Turkmen / Russian', currency: 'Turkmenistani manat (m)', dish: 'Plov & shashlik', phrases: [['Hello','Salam'],['Thank you','Sag boluň'],['Cheers','Saglygyňyza']] },
  'Timor-Leste': { lang: 'Tetum / Portuguese', currency: 'US dollar ($)', dish: 'Ikan sabuko & batar daan', phrases: [['Hello','Bondia'],['Thank you','Obrigadu'],['Cheers','Saúde']] },
  'Ecuador': { lang: 'Spanish / Quechua', currency: 'US dollar ($)', dish: 'Ceviche & llapingachos', phrases: [['Hello','Hola'],['Thank you','Gracias'],['Cheers','Salud']] },
  'Venezuela': { lang: 'Spanish', currency: 'Venezuelan bolívar (Bs)', dish: 'Arepas & pabellón criollo', phrases: [['Hello','Hola'],['Thank you','Gracias'],['Cheers','Salud']] },
  'Guyana': { lang: 'English / Creole', currency: 'Guyanese dollar (G$)', dish: 'Pepperpot & cook-up rice', phrases: [['Hello','Hello'],['Thank you','Thank you'],['Cheers','Cheers']] },
  'Suriname': { lang: 'Dutch / Sranan Tongo', currency: 'Surinamese dollar (SRD)', dish: 'Roti & pom', phrases: [['Hello','Hallo / Fa waka'],['Thank you','Dank u / Grantangi'],['Cheers','Proost']] },
  /* === end world-expansion === */

};

/* ISO 3166-1 alpha-2 codes — used to pull local radio by country. */
const COUNTRY_CODES = {
  'Albania':'AL','Austria':'AT','Belgium':'BE','Bosnia and Herzegovina':'BA',
  'Bulgaria':'BG','Canada':'CA','Croatia':'HR','Cyprus':'CY','Czech Republic':'CZ',
  'Denmark':'DK','England':'GB','Estonia':'EE','Faroe Islands':'FO','Finland':'FI',
  'France':'FR','Germany':'DE','Greece':'GR','Hungary':'HU','Iceland':'IS',
  'Ireland':'IE','Italy':'IT','Malta':'MT','Montenegro':'ME','Netherlands':'NL',
  'Norway':'NO','Poland':'PL','Portugal':'PT','Romania':'RO','Spain':'ES',
  'Sweden':'SE','Switzerland':'CH','Turkey':'TR','United Kingdom':'GB','United States':'US',
  'Mexico':'MX','Indonesia':'ID','Micronesia':'FM','Bahamas':'BS','Brazil':'BR',
  'Chile':'CL','Peru':'PE',
  /* === world-expansion countries (build_culture.py) — review phrases/dishes === */
  'Japan':'JP',
  'China':'CN',
  'India':'IN',
  'South Korea':'KR',
  'Thailand':'TH',
  'Malaysia':'MY',
  'Singapore':'SG',
  'Philippines':'PH',
  'Vietnam':'VN',
  'Cambodia':'KH',
  'Laos':'LA',
  'Taiwan':'TW',
  'Mongolia':'MN',
  'Sri Lanka':'LK',
  'Israel':'IL',
  'United Arab Emirates':'AE',
  'Saudi Arabia':'SA',
  'Qatar':'QA',
  'Jordan':'JO',
  'Iran':'IR',
  'Armenia':'AM',
  'Azerbaijan':'AZ',
  'Georgia':'GE',
  'North Korea':'KP',
  'Morocco':'MA',
  'Egypt':'EG',
  'Kenya':'KE',
  'Senegal':'SN',
  'Ethiopia':'ET',
  'Gambia':'GM',
  'South Africa':'ZA',
  'Namibia':'NA',
  'Zimbabwe':'ZW',
  'DR Congo':'CD',
  'Tunisia':'TN',
  'Algeria':'DZ',
  'Libya':'LY',
  'Sudan':'SD',
  'South Sudan':'SS',
  'Mauritania':'MR',
  'Mali':'ML',
  'Niger':'NE',
  'Chad':'TD',
  'Burkina Faso':'BF',
  'Nigeria':'NG',
  'Ghana':'GH',
  'Togo':'TG',
  'Benin':'BJ',
  'Côte d\'Ivoire':'CI',
  'Guinea':'GN',
  'Guinea-Bissau':'GW',
  'Sierra Leone':'SL',
  'Liberia':'LR',
  'Cape Verde':'CV',
  'Cameroon':'CM',
  'Gabon':'GA',
  'Republic of the Congo':'CG',
  'Central African Republic':'CF',
  'Equatorial Guinea':'GQ',
  'São Tomé and Príncipe':'ST',
  'Angola':'AO',
  'Uganda':'UG',
  'Rwanda':'RW',
  'Burundi':'BI',
  'Tanzania':'TZ',
  'Eritrea':'ER',
  'Djibouti':'DJ',
  'Somalia':'SO',
  'Madagascar':'MG',
  'Mauritius':'MU',
  'Seychelles':'SC',
  'Comoros':'KM',
  'Malawi':'MW',
  'Mozambique':'MZ',
  'Zambia':'ZM',
  'Botswana':'BW',
  'Lesotho':'LS',
  'Eswatini':'SZ',
  'Australia':'AU',
  'New Zealand':'NZ',
  'Papua New Guinea':'PG',
  'Fiji':'FJ',
  'Solomon Islands':'SB',
  'Vanuatu':'VU',
  'New Caledonia':'NC',
  'Samoa':'WS',
  'American Samoa':'AS',
  'Tonga':'TO',
  'Cook Islands':'CK',
  'French Polynesia':'PF',
  'Niue':'NU',
  'Kiribati':'KI',
  'Tuvalu':'TV',
  'Nauru':'NR',
  'Palau':'PW',
  'Marshall Islands':'MH',
  'Guam':'GU',
  'Northern Mariana Islands':'MP',
  'Norfolk Island':'NF',
  'Pitcairn Islands':'PN',
  'Argentina':'AR',
  'Bolivia':'BO',
  'Colombia':'CO',
  'Uruguay':'UY',
  'Paraguay':'PY',
  'Cuba':'CU',
  'Costa Rica':'CR',
  'Belize':'BZ',
  'Ukraine':'UA',
  'Serbia':'RS',
  'Luxembourg':'LU',
  'Lithuania':'LT',
  'Latvia':'LV',
  'Moldova':'MD',
  'Slovakia':'SK',
  'Slovenia':'SI',
  'Vatican City':'VA',
  'Russia':'RU',
  'Belarus':'BY',
  'Brunei':'BN',
  'Myanmar':'MM',
  'Kazakhstan':'KZ',
  'Uzbekistan':'UZ',
  'Kyrgyzstan':'KG',
  'Tajikistan':'TJ',
  'Turkmenistan':'TM',
  'Timor-Leste':'TL',
  'Ecuador':'EC',
  'Venezuela':'VE',
  'Guyana':'GY',
  'Suriname':'SR',
  /* === end world-expansion === */

};

/* ISO 4217 currency codes — used for live exchange rates. */
const CURRENCY_CODES = {
  'Albania':'ALL','Austria':'EUR','Belgium':'EUR','Bosnia and Herzegovina':'BAM',
  'Bulgaria':'BGN','Canada':'CAD','Croatia':'EUR','Cyprus':'EUR','Czech Republic':'CZK',
  'Denmark':'DKK','England':'GBP','Estonia':'EUR','Faroe Islands':'DKK','Finland':'EUR',
  'France':'EUR','Germany':'EUR','Greece':'EUR','Hungary':'HUF','Iceland':'ISK',
  'Ireland':'EUR','Italy':'EUR','Malta':'EUR','Montenegro':'EUR','Netherlands':'EUR',
  'Norway':'NOK','Poland':'PLN','Portugal':'EUR','Romania':'RON','Spain':'EUR',
  'Sweden':'SEK','Switzerland':'CHF','Turkey':'TRY','United Kingdom':'GBP','United States':'USD',
  'Mexico':'MXN','Indonesia':'IDR','Micronesia':'USD','Bahamas':'BSD','Brazil':'BRL',
  'Chile':'CLP','Peru':'PEN',
  /* === world-expansion countries (build_culture.py) — review phrases/dishes === */
  'Japan':'JPY',
  'China':'CNY',
  'India':'INR',
  'South Korea':'KRW',
  'Thailand':'THB',
  'Malaysia':'MYR',
  'Singapore':'SGD',
  'Philippines':'PHP',
  'Vietnam':'VND',
  'Cambodia':'KHR',
  'Laos':'LAK',
  'Taiwan':'TWD',
  'Mongolia':'MNT',
  'Sri Lanka':'LKR',
  'Israel':'ILS',
  'United Arab Emirates':'AED',
  'Saudi Arabia':'SAR',
  'Qatar':'QAR',
  'Jordan':'JOD',
  'Iran':'IRR',
  'Armenia':'AMD',
  'Azerbaijan':'AZN',
  'Georgia':'GEL',
  'North Korea':'KPW',
  'Morocco':'MAD',
  'Egypt':'EGP',
  'Kenya':'KES',
  'Senegal':'XOF',
  'Ethiopia':'ETB',
  'Gambia':'GMD',
  'South Africa':'ZAR',
  'Namibia':'NAD',
  'Zimbabwe':'ZWL',
  'DR Congo':'CDF',
  'Tunisia':'TND',
  'Algeria':'DZD',
  'Libya':'LYD',
  'Sudan':'SDG',
  'South Sudan':'SSP',
  'Mauritania':'MRU',
  'Mali':'XOF',
  'Niger':'XOF',
  'Chad':'XAF',
  'Burkina Faso':'XOF',
  'Nigeria':'NGN',
  'Ghana':'GHS',
  'Togo':'XOF',
  'Benin':'XOF',
  'Côte d\'Ivoire':'XOF',
  'Guinea':'GNF',
  'Guinea-Bissau':'XOF',
  'Sierra Leone':'SLE',
  'Liberia':'LRD',
  'Cape Verde':'CVE',
  'Cameroon':'XAF',
  'Gabon':'XAF',
  'Republic of the Congo':'XAF',
  'Central African Republic':'XAF',
  'Equatorial Guinea':'XAF',
  'São Tomé and Príncipe':'STN',
  'Angola':'AOA',
  'Uganda':'UGX',
  'Rwanda':'RWF',
  'Burundi':'BIF',
  'Tanzania':'TZS',
  'Eritrea':'ERN',
  'Djibouti':'DJF',
  'Somalia':'SOS',
  'Madagascar':'MGA',
  'Mauritius':'MUR',
  'Seychelles':'SCR',
  'Comoros':'KMF',
  'Malawi':'MWK',
  'Mozambique':'MZN',
  'Zambia':'ZMW',
  'Botswana':'BWP',
  'Lesotho':'LSL',
  'Eswatini':'SZL',
  'Australia':'AUD',
  'New Zealand':'NZD',
  'Papua New Guinea':'PGK',
  'Fiji':'FJD',
  'Solomon Islands':'SBD',
  'Vanuatu':'VUV',
  'New Caledonia':'XPF',
  'Samoa':'WST',
  'American Samoa':'USD',
  'Tonga':'TOP',
  'Cook Islands':'NZD',
  'French Polynesia':'XPF',
  'Niue':'NZD',
  'Kiribati':'AUD',
  'Tuvalu':'AUD',
  'Nauru':'AUD',
  'Palau':'USD',
  'Marshall Islands':'USD',
  'Guam':'USD',
  'Northern Mariana Islands':'USD',
  'Norfolk Island':'AUD',
  'Pitcairn Islands':'NZD',
  'Argentina':'ARS',
  'Bolivia':'BOB',
  'Colombia':'COP',
  'Uruguay':'UYU',
  'Paraguay':'PYG',
  'Cuba':'CUP',
  'Costa Rica':'CRC',
  'Belize':'BZD',
  'Ukraine':'UAH',
  'Serbia':'RSD',
  'Luxembourg':'EUR',
  'Lithuania':'EUR',
  'Latvia':'EUR',
  'Moldova':'MDL',
  'Slovakia':'EUR',
  'Slovenia':'EUR',
  'Vatican City':'EUR',
  'Russia':'RUB',
  'Belarus':'BYN',
  'Brunei':'BND',
  'Myanmar':'MMK',
  'Kazakhstan':'KZT',
  'Uzbekistan':'UZS',
  'Kyrgyzstan':'KGS',
  'Tajikistan':'TJS',
  'Turkmenistan':'TMT',
  'Timor-Leste':'USD',
  'Ecuador':'USD',
  'Venezuela':'VES',
  'Guyana':'GYD',
  'Suriname':'SRD',
  /* === end world-expansion === */

};

/* Quick country facts — capital, rough population, which side they
   drive on, and the plug/voltage you'll need. Hardcoded so it's
   instant and never depends on a flaky API. */
const COUNTRY_FACTS = {
  'Albania':{capital:'Tirana',pop:'2.8M',drives:'Right',plug:'Type C/F · 230V'},
  'Austria':{capital:'Vienna',pop:'9.0M',drives:'Right',plug:'Type C/F · 230V'},
  'Belgium':{capital:'Brussels',pop:'11.7M',drives:'Right',plug:'Type C/E · 230V'},
  'Bosnia and Herzegovina':{capital:'Sarajevo',pop:'3.2M',drives:'Right',plug:'Type C/F · 230V'},
  'Bulgaria':{capital:'Sofia',pop:'6.4M',drives:'Right',plug:'Type C/F · 230V'},
  'Canada':{capital:'Ottawa',pop:'40M',drives:'Right',plug:'Type A/B · 120V'},
  'Croatia':{capital:'Zagreb',pop:'3.9M',drives:'Right',plug:'Type C/F · 230V'},
  'Cyprus':{capital:'Nicosia',pop:'1.2M',drives:'Left',plug:'Type G · 230V'},
  'Czech Republic':{capital:'Prague',pop:'10.5M',drives:'Right',plug:'Type C/E · 230V'},
  'Denmark':{capital:'Copenhagen',pop:'5.9M',drives:'Right',plug:'Type C/E/K · 230V'},
  'England':{capital:'London',pop:'56M',drives:'Left',plug:'Type G · 230V'},
  'Estonia':{capital:'Tallinn',pop:'1.3M',drives:'Right',plug:'Type C/F · 230V'},
  'Faroe Islands':{capital:'Tórshavn',pop:'54K',drives:'Right',plug:'Type C/F/K · 230V'},
  'Finland':{capital:'Helsinki',pop:'5.6M',drives:'Right',plug:'Type C/F · 230V'},
  'France':{capital:'Paris',pop:'68M',drives:'Right',plug:'Type C/E · 230V'},
  'Germany':{capital:'Berlin',pop:'84M',drives:'Right',plug:'Type C/F · 230V'},
  'Greece':{capital:'Athens',pop:'10.4M',drives:'Right',plug:'Type C/F · 230V'},
  'Hungary':{capital:'Budapest',pop:'9.6M',drives:'Right',plug:'Type C/F · 230V'},
  'Iceland':{capital:'Reykjavík',pop:'380K',drives:'Right',plug:'Type C/F · 230V'},
  'Ireland':{capital:'Dublin',pop:'5.1M',drives:'Left',plug:'Type G · 230V'},
  'Italy':{capital:'Rome',pop:'59M',drives:'Right',plug:'Type C/F/L · 230V'},
  'Malta':{capital:'Valletta',pop:'535K',drives:'Left',plug:'Type G · 230V'},
  'Montenegro':{capital:'Podgorica',pop:'620K',drives:'Right',plug:'Type C/F · 230V'},
  'Netherlands':{capital:'Amsterdam',pop:'17.8M',drives:'Right',plug:'Type C/F · 230V'},
  'Norway':{capital:'Oslo',pop:'5.5M',drives:'Right',plug:'Type C/F · 230V'},
  'Poland':{capital:'Warsaw',pop:'37.7M',drives:'Right',plug:'Type C/E · 230V'},
  'Portugal':{capital:'Lisbon',pop:'10.3M',drives:'Right',plug:'Type C/F · 230V'},
  'Romania':{capital:'Bucharest',pop:'19M',drives:'Right',plug:'Type C/F · 230V'},
  'Spain':{capital:'Madrid',pop:'48M',drives:'Right',plug:'Type C/F · 230V'},
  'Sweden':{capital:'Stockholm',pop:'10.5M',drives:'Right',plug:'Type C/F · 230V'},
  'Switzerland':{capital:'Bern',pop:'8.8M',drives:'Right',plug:'Type C/J · 230V'},
  'Turkey':{capital:'Ankara',pop:'85M',drives:'Right',plug:'Type C/F · 230V'},
  'United Kingdom':{capital:'London',pop:'67M',drives:'Left',plug:'Type G · 230V'},
  'United States':{capital:'Washington, D.C.',pop:'335M',drives:'Right',plug:'Type A/B · 120V'},
  'Mexico':{capital:'Mexico City',pop:'129M',drives:'Right',plug:'Type A/B · 127V'},
  'Indonesia':{capital:'Jakarta',pop:'277M',drives:'Left',plug:'Type C/F · 230V'},
  'Micronesia':{capital:'Palikir',pop:'113K',drives:'Right',plug:'Type A/B · 120V'},
  'Bahamas':{capital:'Nassau',pop:'410K',drives:'Left',plug:'Type A/B · 120V'},
  'Brazil':{capital:'Brasília',pop:'216M',drives:'Right',plug:'Type C/N · 127/220V'},
  'Chile':{capital:'Santiago',pop:'19.6M',drives:'Right',plug:'Type C/L · 220V'},
  'Peru':{capital:'Lima',pop:'34M',drives:'Right',plug:'Type A/C · 220V'},
  /* === world-expansion countries (build_culture.py) — review phrases/dishes === */
  'Japan':{capital:'Tokyo',pop:'124M',drives:'Left',plug:'Type A/B · 100V'},
  'China':{capital:'Beijing',pop:'1.41B',drives:'Right',plug:'Type A/I · 220V'},
  'India':{capital:'New Delhi',pop:'1.43B',drives:'Left',plug:'Type C/D/M · 230V'},
  'South Korea':{capital:'Seoul',pop:'52M',drives:'Right',plug:'Type C/F · 220V'},
  'Thailand':{capital:'Bangkok',pop:'72M',drives:'Left',plug:'Type A/B/C · 230V'},
  'Malaysia':{capital:'Kuala Lumpur',pop:'34M',drives:'Left',plug:'Type G · 240V'},
  'Singapore':{capital:'Singapore',pop:'5.9M',drives:'Left',plug:'Type G · 230V'},
  'Philippines':{capital:'Manila',pop:'117M',drives:'Right',plug:'Type A/B/C · 220V'},
  'Vietnam':{capital:'Hanoi',pop:'99M',drives:'Right',plug:'Type A/C · 220V'},
  'Cambodia':{capital:'Phnom Penh',pop:'17M',drives:'Right',plug:'Type A/C/G · 230V'},
  'Laos':{capital:'Vientiane',pop:'7.6M',drives:'Right',plug:'Type A/B/C · 230V'},
  'Taiwan':{capital:'Taipei',pop:'23M',drives:'Right',plug:'Type A/B · 110V'},
  'Mongolia':{capital:'Ulaanbaatar',pop:'3.4M',drives:'Right',plug:'Type C/E · 220V'},
  'Sri Lanka':{capital:'Colombo',pop:'22M',drives:'Left',plug:'Type D/G/M · 230V'},
  'Israel':{capital:'Jerusalem',pop:'9.8M',drives:'Right',plug:'Type C/H · 230V'},
  'United Arab Emirates':{capital:'Abu Dhabi',pop:'9.5M',drives:'Right',plug:'Type G · 230V'},
  'Saudi Arabia':{capital:'Riyadh',pop:'37M',drives:'Right',plug:'Type G · 230V'},
  'Qatar':{capital:'Doha',pop:'2.7M',drives:'Right',plug:'Type D/G · 240V'},
  'Jordan':{capital:'Amman',pop:'11M',drives:'Right',plug:'Type C/D/F/G · 230V'},
  'Iran':{capital:'Tehran',pop:'89M',drives:'Right',plug:'Type C/F · 230V'},
  'Armenia':{capital:'Yerevan',pop:'3.0M',drives:'Right',plug:'Type C/F · 230V'},
  'Azerbaijan':{capital:'Baku',pop:'10M',drives:'Right',plug:'Type C/F · 220V'},
  'Georgia':{capital:'Tbilisi',pop:'3.7M',drives:'Right',plug:'Type C/F · 220V'},
  'North Korea':{capital:'Pyongyang',pop:'26M',drives:'Right',plug:'Type A/C/F · 220V'},
  'Morocco':{capital:'Rabat',pop:'37M',drives:'Right',plug:'Type C/E · 220V'},
  'Egypt':{capital:'Cairo',pop:'113M',drives:'Right',plug:'Type C/F · 220V'},
  'Kenya':{capital:'Nairobi',pop:'55M',drives:'Left',plug:'Type G · 240V'},
  'Senegal':{capital:'Dakar',pop:'18M',drives:'Right',plug:'Type C/D/E/K · 230V'},
  'Ethiopia':{capital:'Addis Ababa',pop:'127M',drives:'Right',plug:'Type C/F · 220V'},
  'Gambia':{capital:'Banjul',pop:'2.7M',drives:'Right',plug:'Type G · 230V'},
  'South Africa':{capital:'Pretoria',pop:'60M',drives:'Left',plug:'Type M/N · 230V'},
  'Namibia':{capital:'Windhoek',pop:'2.6M',drives:'Left',plug:'Type D/M · 220V'},
  'Zimbabwe':{capital:'Harare',pop:'16M',drives:'Left',plug:'Type D/G · 220V'},
  'DR Congo':{capital:'Kinshasa',pop:'102M',drives:'Right',plug:'Type C/D/E · 220V'},
  'Tunisia':{capital:'Tunis',pop:'12M',drives:'Right',plug:'Type C/E · 230V'},
  'Algeria':{capital:'Algiers',pop:'46M',drives:'Right',plug:'Type C/F · 230V'},
  'Libya':{capital:'Tripoli',pop:'7.3M',drives:'Right',plug:'Type C/L · 230V'},
  'Sudan':{capital:'Khartoum',pop:'48M',drives:'Right',plug:'Type C/D · 230V'},
  'South Sudan':{capital:'Juba',pop:'11M',drives:'Right',plug:'Type C/D · 230V'},
  'Mauritania':{capital:'Nouakchott',pop:'4.9M',drives:'Right',plug:'Type C · 220V'},
  'Mali':{capital:'Bamako',pop:'23M',drives:'Right',plug:'Type C/E · 220V'},
  'Niger':{capital:'Niamey',pop:'26M',drives:'Right',plug:'Type C/D/E/F · 220V'},
  'Chad':{capital:'N\'Djamena',pop:'18M',drives:'Right',plug:'Type C/D/E/F · 220V'},
  'Burkina Faso':{capital:'Ouagadougou',pop:'23M',drives:'Right',plug:'Type C/E · 220V'},
  'Nigeria':{capital:'Abuja',pop:'224M',drives:'Right',plug:'Type D/G · 230V'},
  'Ghana':{capital:'Accra',pop:'34M',drives:'Right',plug:'Type D/G · 230V'},
  'Togo':{capital:'Lomé',pop:'9.1M',drives:'Right',plug:'Type C · 220V'},
  'Benin':{capital:'Porto-Novo',pop:'13M',drives:'Right',plug:'Type C/E · 220V'},
  'Côte d\'Ivoire':{capital:'Yamoussoukro',pop:'29M',drives:'Right',plug:'Type C/E · 220V'},
  'Guinea':{capital:'Conakry',pop:'14M',drives:'Right',plug:'Type C/F/K · 220V'},
  'Guinea-Bissau':{capital:'Bissau',pop:'2.2M',drives:'Right',plug:'Type C · 220V'},
  'Sierra Leone':{capital:'Freetown',pop:'8.6M',drives:'Right',plug:'Type D/G · 230V'},
  'Liberia':{capital:'Monrovia',pop:'5.4M',drives:'Right',plug:'Type A/B/C/F · 120V'},
  'Cape Verde':{capital:'Praia',pop:'600K',drives:'Right',plug:'Type C/F · 220V'},
  'Cameroon':{capital:'Yaoundé',pop:'28M',drives:'Right',plug:'Type C/E · 220V'},
  'Gabon':{capital:'Libreville',pop:'2.4M',drives:'Right',plug:'Type C · 220V'},
  'Republic of the Congo':{capital:'Brazzaville',pop:'6.1M',drives:'Right',plug:'Type C/E · 230V'},
  'Central African Republic':{capital:'Bangui',pop:'5.7M',drives:'Right',plug:'Type C/E · 220V'},
  'Equatorial Guinea':{capital:'Malabo',pop:'1.7M',drives:'Right',plug:'Type C/E · 220V'},
  'São Tomé and Príncipe':{capital:'São Tomé',pop:'230K',drives:'Right',plug:'Type C/F · 220V'},
  'Angola':{capital:'Luanda',pop:'36M',drives:'Right',plug:'Type C · 220V'},
  'Uganda':{capital:'Kampala',pop:'48M',drives:'Left',plug:'Type G · 240V'},
  'Rwanda':{capital:'Kigali',pop:'14M',drives:'Right',plug:'Type C/J · 230V'},
  'Burundi':{capital:'Gitega',pop:'13M',drives:'Right',plug:'Type C/E · 220V'},
  'Tanzania':{capital:'Dodoma',pop:'67M',drives:'Left',plug:'Type D/G · 230V'},
  'Eritrea':{capital:'Asmara',pop:'3.7M',drives:'Right',plug:'Type C/L · 230V'},
  'Djibouti':{capital:'Djibouti City',pop:'1.1M',drives:'Right',plug:'Type C/E · 220V'},
  'Somalia':{capital:'Mogadishu',pop:'18M',drives:'Right',plug:'Type C · 220V'},
  'Madagascar':{capital:'Antananarivo',pop:'30M',drives:'Right',plug:'Type C/E · 220V'},
  'Mauritius':{capital:'Port Louis',pop:'1.3M',drives:'Left',plug:'Type C/G · 230V'},
  'Seychelles':{capital:'Victoria',pop:'100K',drives:'Left',plug:'Type G · 240V'},
  'Comoros':{capital:'Moroni',pop:'850K',drives:'Right',plug:'Type C/E · 220V'},
  'Malawi':{capital:'Lilongwe',pop:'21M',drives:'Left',plug:'Type G · 230V'},
  'Mozambique':{capital:'Maputo',pop:'33M',drives:'Left',plug:'Type C/F/M · 220V'},
  'Zambia':{capital:'Lusaka',pop:'20M',drives:'Left',plug:'Type C/D/G · 230V'},
  'Botswana':{capital:'Gaborone',pop:'2.7M',drives:'Left',plug:'Type D/G/M · 230V'},
  'Lesotho':{capital:'Maseru',pop:'2.3M',drives:'Left',plug:'Type M · 220V'},
  'Eswatini':{capital:'Mbabane',pop:'1.2M',drives:'Left',plug:'Type M · 230V'},
  'Australia':{capital:'Canberra',pop:'26M',drives:'Left',plug:'Type I · 230V'},
  'New Zealand':{capital:'Wellington',pop:'5.2M',drives:'Left',plug:'Type I · 230V'},
  'Papua New Guinea':{capital:'Port Moresby',pop:'10M',drives:'Right',plug:'Type I · 240V'},
  'Fiji':{capital:'Suva',pop:'930K',drives:'Left',plug:'Type I · 240V'},
  'Solomon Islands':{capital:'Honiara',pop:'740K',drives:'Left',plug:'Type I · 220V'},
  'Vanuatu':{capital:'Port Vila',pop:'330K',drives:'Right',plug:'Type I · 220V'},
  'New Caledonia':{capital:'Nouméa',pop:'270K',drives:'Right',plug:'Type C/E · 220V'},
  'Samoa':{capital:'Apia',pop:'220K',drives:'Left',plug:'Type I · 230V'},
  'American Samoa':{capital:'Pago Pago',pop:'45K',drives:'Right',plug:'Type A/B · 120V'},
  'Tonga':{capital:'Nukuʻalofa',pop:'105K',drives:'Left',plug:'Type I · 240V'},
  'Cook Islands':{capital:'Avarua',pop:'15K',drives:'Left',plug:'Type I · 240V'},
  'French Polynesia':{capital:'Papeete',pop:'280K',drives:'Right',plug:'Type C/E · 220V'},
  'Niue':{capital:'Alofi',pop:'1.9K',drives:'Left',plug:'Type I · 240V'},
  'Kiribati':{capital:'South Tarawa',pop:'130K',drives:'Left',plug:'Type I · 240V'},
  'Tuvalu':{capital:'Funafuti',pop:'11K',drives:'Left',plug:'Type I · 240V'},
  'Nauru':{capital:'Yaren',pop:'12K',drives:'Left',plug:'Type I · 240V'},
  'Palau':{capital:'Ngerulmud',pop:'18K',drives:'Right',plug:'Type A/B · 120V'},
  'Marshall Islands':{capital:'Majuro',pop:'42K',drives:'Right',plug:'Type A/B · 120V'},
  'Guam':{capital:'Hagåtña',pop:'170K',drives:'Right',plug:'Type A/B · 110V'},
  'Northern Mariana Islands':{capital:'Saipan',pop:'47K',drives:'Right',plug:'Type A/B · 120V'},
  'Norfolk Island':{capital:'Kingston',pop:'2.2K',drives:'Left',plug:'Type I · 240V'},
  'Pitcairn Islands':{capital:'Adamstown',pop:'35',drives:'Left',plug:'Type I · 240V'},
  'Argentina':{capital:'Buenos Aires',pop:'46M',drives:'Right',plug:'Type C/I · 220V'},
  'Bolivia':{capital:'Sucre',pop:'12M',drives:'Right',plug:'Type A/C · 230V'},
  'Colombia':{capital:'Bogotá',pop:'52M',drives:'Right',plug:'Type A/B · 110V'},
  'Uruguay':{capital:'Montevideo',pop:'3.4M',drives:'Right',plug:'Type C/F/L · 230V'},
  'Paraguay':{capital:'Asunción',pop:'6.9M',drives:'Right',plug:'Type C · 220V'},
  'Cuba':{capital:'Havana',pop:'11M',drives:'Right',plug:'Type A/B/C · 110/220V'},
  'Costa Rica':{capital:'San José',pop:'5.2M',drives:'Right',plug:'Type A/B · 120V'},
  'Belize':{capital:'Belmopan',pop:'410K',drives:'Right',plug:'Type A/B/G · 110/220V'},
  'Ukraine':{capital:'Kyiv',pop:'38M',drives:'Right',plug:'Type C/F · 230V'},
  'Serbia':{capital:'Belgrade',pop:'6.6M',drives:'Right',plug:'Type C/F · 230V'},
  'Luxembourg':{capital:'Luxembourg City',pop:'660K',drives:'Right',plug:'Type C/F · 230V'},
  'Lithuania':{capital:'Vilnius',pop:'2.9M',drives:'Right',plug:'Type C/F · 230V'},
  'Latvia':{capital:'Riga',pop:'1.9M',drives:'Right',plug:'Type C/F · 230V'},
  'Moldova':{capital:'Chișinău',pop:'2.6M',drives:'Right',plug:'Type C/F · 230V'},
  'Slovakia':{capital:'Bratislava',pop:'5.4M',drives:'Right',plug:'Type C/E · 230V'},
  'Slovenia':{capital:'Ljubljana',pop:'2.1M',drives:'Right',plug:'Type C/F · 230V'},
  'Vatican City':{capital:'Vatican City',pop:'800',drives:'Right',plug:'Type C/F/L · 230V'},
  'Russia':{capital:'Moscow',pop:'144M',drives:'Right',plug:'Type C/F · 230V'},
  'Belarus':{capital:'Minsk',pop:'9.2M',drives:'Right',plug:'Type C/F · 230V'},
  'Brunei':{capital:'Bandar Seri Begawan',pop:'460K',drives:'Left',plug:'Type G · 240V'},
  'Myanmar':{capital:'Naypyidaw',pop:'54M',drives:'Right',plug:'Type C/D/G · 230V'},
  'Kazakhstan':{capital:'Astana',pop:'20M',drives:'Right',plug:'Type C/F · 220V'},
  'Uzbekistan':{capital:'Tashkent',pop:'36M',drives:'Right',plug:'Type C/F · 220V'},
  'Kyrgyzstan':{capital:'Bishkek',pop:'7.0M',drives:'Right',plug:'Type C/F · 220V'},
  'Tajikistan':{capital:'Dushanbe',pop:'10M',drives:'Right',plug:'Type C/F · 220V'},
  'Turkmenistan':{capital:'Ashgabat',pop:'6.5M',drives:'Right',plug:'Type C/F · 220V'},
  'Timor-Leste':{capital:'Dili',pop:'1.4M',drives:'Left',plug:'Type C/E/F/I · 220V'},
  'Ecuador':{capital:'Quito',pop:'18M',drives:'Right',plug:'Type A/B · 120V'},
  'Venezuela':{capital:'Caracas',pop:'28M',drives:'Right',plug:'Type A/B · 120V'},
  'Guyana':{capital:'Georgetown',pop:'810K',drives:'Left',plug:'Type A/B/D/G · 240V'},
  'Suriname':{capital:'Paramaribo',pop:'620K',drives:'Left',plug:'Type C/F · 127V'},
  /* === end world-expansion === */

};

const Culture = {
  get(country) {
    return COUNTRY_PROFILES[country] || {
      lang: '—', currency: '—', dish: 'Local specialities',
      phrases: [['Hello','Hello'],['Thank you','Thank you'],['Cheers','Cheers']]
    };
  },
  code(country)         { return COUNTRY_CODES[country] || null; },
  currencyCode(country) { return CURRENCY_CODES[country] || null; },
  facts(country)        { return COUNTRY_FACTS[country] || null; }
};

/* ---- WMO weather code → icon + label (day/night aware) ---- */
function weatherInfo(code, isDay = 1) {
  const day = isDay ? 1 : 0;
  const map = {
    0:  [day ? '☀️' : '🌙', day ? 'Clear sky' : 'Clear night'],
    1:  [day ? '🌤️' : '🌙', 'Mainly clear'],
    2:  [day ? '⛅' : '☁️', 'Partly cloudy'],
    3:  ['☁️', 'Overcast'],
    45: ['🌫️', 'Foggy'],  48: ['🌫️', 'Rime fog'],
    51: ['🌦️', 'Light drizzle'], 53: ['🌦️', 'Drizzle'], 55: ['🌦️', 'Heavy drizzle'],
    56: ['🌧️', 'Freezing drizzle'], 57: ['🌧️', 'Freezing drizzle'],
    61: ['🌧️', 'Light rain'], 63: ['🌧️', 'Rain'], 65: ['🌧️', 'Heavy rain'],
    66: ['🌧️', 'Freezing rain'], 67: ['🌧️', 'Freezing rain'],
    71: ['🌨️', 'Light snow'], 73: ['🌨️', 'Snow'], 75: ['❄️', 'Heavy snow'], 77: ['🌨️', 'Snow grains'],
    80: ['🌦️', 'Rain showers'], 81: ['🌦️', 'Rain showers'], 82: ['⛈️', 'Violent showers'],
    85: ['🌨️', 'Snow showers'], 86: ['🌨️', 'Snow showers'],
    95: ['⛈️', 'Thunderstorm'], 96: ['⛈️', 'Storm & hail'], 99: ['⛈️', 'Storm & hail']
  };
  const [icon, label] = map[code] || ['🌍', 'Clear'];
  return { icon, label };
}

export { Culture, weatherInfo };
