/* ============================================================
   CULTURE — per-country "local flavour": language, a few key
   phrases (native script + how to say it), currency, and a
   signature dish. Keyed by the country name used in the data.
   Phrases: [greeting, thank you, cheers].
   ============================================================ */
const COUNTRY_PROFILES = {
  'Albania':        { lang: 'Albanian',   currency: 'Albanian lek (L)',         dish: 'Tavë kosi — baked lamb with yogurt',
    phrases: [['Hello','Përshëndetje'],['Thank you','Faleminderit'],['Cheers','Gëzuar']] },
  'Austria':        { lang: 'German',      currency: 'Euro (€)',                 dish: 'Wiener Schnitzel & Sachertorte',
    phrases: [['Hello','Grüß Gott'],['Thank you','Danke'],['Cheers','Prost']] },
  'Belgium':        { lang: 'Dutch / French', currency: 'Euro (€)',             dish: 'Moules-frites & waffles',
    phrases: [['Hello','Hallo / Bonjour'],['Thank you','Dank u / Merci'],['Cheers','Proost / Santé']] },
  'Bosnia and Herzegovina': { lang: 'Bosnian', currency: 'Convertible mark (KM)', dish: 'Ćevapi with somun bread',
    phrases: [['Hello','Zdravo'],['Thank you','Hvala'],['Cheers','Živjeli']] },
  'Bulgaria':       { lang: 'Bulgarian',   currency: 'Bulgarian lev (лв)',       dish: 'Banitsa & shopska salad',
    phrases: [['Hello','Здравей · Zdravey'],['Thank you','Благодаря · Blagodarya'],['Cheers','Наздраве · Nazdrave']] },
  'Canada':         { lang: 'English / French', currency: 'Canadian dollar (C$)', dish: 'Poutine & butter tarts',
    phrases: [['Hello','Hello / Bonjour'],['Thank you','Thanks / Merci'],['Cheers','Cheers / Santé']] },
  'Croatia':        { lang: 'Croatian',    currency: 'Euro (€)',                 dish: 'Peka & black risotto',
    phrases: [['Hello','Bok'],['Thank you','Hvala'],['Cheers','Živjeli']] },
  'Cyprus':         { lang: 'Greek / Turkish', currency: 'Euro (€)',             dish: 'Halloumi & souvlaki',
    phrases: [['Hello','Γειά σου · Yiá sou'],['Thank you','Ευχαριστώ · Efharistó'],['Cheers','Γειά μας · Yiá mas']] },
  'Czech Republic': { lang: 'Czech',       currency: 'Czech koruna (Kč)',        dish: 'Svíčková & trdelník',
    phrases: [['Hello','Ahoj'],['Thank you','Děkuji'],['Cheers','Na zdraví']] },
  'Denmark':        { lang: 'Danish',      currency: 'Danish krone (kr)',        dish: 'Smørrebrød open sandwiches',
    phrases: [['Hello','Hej'],['Thank you','Tak'],['Cheers','Skål']] },
  'England':        { lang: 'English',     currency: 'Pound sterling (£)',       dish: 'Fish & chips, Sunday roast',
    phrases: [['Hello','Hello'],['Thank you','Thank you / Ta'],['Cheers','Cheers']] },
  'Estonia':        { lang: 'Estonian',    currency: 'Euro (€)',                 dish: 'Mulgipuder & black bread',
    phrases: [['Hello','Tere'],['Thank you','Aitäh'],['Cheers','Terviseks']] },
  'Faroe Islands':  { lang: 'Faroese',     currency: 'Danish krone (kr)',        dish: 'Ræst lamb & fresh fish',
    phrases: [['Hello','Halló'],['Thank you','Takk'],['Cheers','Skál']] },
  'Finland':        { lang: 'Finnish',     currency: 'Euro (€)',                 dish: 'Karelian pasties & salmon soup',
    phrases: [['Hello','Hei / Moi'],['Thank you','Kiitos'],['Cheers','Kippis']] },
  'France':         { lang: 'French',      currency: 'Euro (€)',                 dish: 'Croissants, coq au vin, fromage',
    phrases: [['Hello','Bonjour'],['Thank you','Merci'],['Cheers','Santé']] },
  'Germany':        { lang: 'German',      currency: 'Euro (€)',                 dish: 'Bratwurst, pretzels & beer',
    phrases: [['Hello','Hallo'],['Thank you','Danke'],['Cheers','Prost']] },
  'Greece':         { lang: 'Greek',       currency: 'Euro (€)',                 dish: 'Moussaka, souvlaki & feta',
    phrases: [['Hello','Γειά σου · Yiá sou'],['Thank you','Ευχαριστώ · Efharistó'],['Cheers','Γειά μας · Yiá mas']] },
  'Hungary':        { lang: 'Hungarian',   currency: 'Forint (Ft)',              dish: 'Goulash & chimney cake',
    phrases: [['Hello','Szia'],['Thank you','Köszönöm'],['Cheers','Egészségedre']] },
  'Iceland':        { lang: 'Icelandic',   currency: 'Icelandic króna (kr)',     dish: 'Plokkfiskur & lamb soup',
    phrases: [['Hello','Halló'],['Thank you','Takk'],['Cheers','Skál']] },
  'Ireland':        { lang: 'Irish / English', currency: 'Euro (€)',             dish: 'Irish stew & soda bread',
    phrases: [['Hello','Dia duit'],['Thank you','Go raibh maith agat'],['Cheers','Sláinte']] },
  'Italy':          { lang: 'Italian',     currency: 'Euro (€)',                 dish: 'Pasta, pizza & gelato',
    phrases: [['Hello','Ciao'],['Thank you','Grazie'],['Cheers','Salute / Cin cin']] },
  'Malta':          { lang: 'Maltese',     currency: 'Euro (€)',                 dish: 'Fenkata (rabbit stew) & pastizzi',
    phrases: [['Hello','Bonġu'],['Thank you','Grazzi'],['Cheers','Saħħa']] },
  'Montenegro':     { lang: 'Montenegrin', currency: 'Euro (€)',                 dish: 'Njeguški pršut & kačamak',
    phrases: [['Hello','Zdravo'],['Thank you','Hvala'],['Cheers','Živjeli']] },
  'Netherlands':    { lang: 'Dutch',       currency: 'Euro (€)',                 dish: 'Stroopwafels & haring',
    phrases: [['Hello','Hallo'],['Thank you','Dank je'],['Cheers','Proost']] },
  'Norway':         { lang: 'Norwegian',   currency: 'Norwegian krone (kr)',     dish: 'Fårikål & brown cheese',
    phrases: [['Hello','Hei'],['Thank you','Takk'],['Cheers','Skål']] },
  'Poland':         { lang: 'Polish',      currency: 'Złoty (zł)',               dish: 'Pierogi & żurek soup',
    phrases: [['Hello','Cześć'],['Thank you','Dziękuję'],['Cheers','Na zdrowie']] },
  'Portugal':       { lang: 'Portuguese',  currency: 'Euro (€)',                 dish: 'Bacalhau & pastéis de nata',
    phrases: [['Hello','Olá'],['Thank you','Obrigado/a'],['Cheers','Saúde']] },
  'Romania':        { lang: 'Romanian',    currency: 'Romanian leu (lei)',       dish: 'Sarmale & mămăligă',
    phrases: [['Hello','Bună'],['Thank you','Mulțumesc'],['Cheers','Noroc']] },
  'Spain':          { lang: 'Spanish',     currency: 'Euro (€)',                 dish: 'Paella, tapas & jamón',
    phrases: [['Hello','Hola'],['Thank you','Gracias'],['Cheers','Salud']] },
  'Sweden':         { lang: 'Swedish',     currency: 'Swedish krona (kr)',       dish: 'Köttbullar & cinnamon buns',
    phrases: [['Hello','Hej'],['Thank you','Tack'],['Cheers','Skål']] },
  'Switzerland':    { lang: 'German / French / Italian', currency: 'Swiss franc (CHF)', dish: 'Fondue, raclette & rösti',
    phrases: [['Hello','Grüezi / Bonjour'],['Thank you','Danke / Merci'],['Cheers','Prost / Santé']] },
  'Turkey':         { lang: 'Turkish',     currency: 'Turkish lira (₺)',         dish: 'Kebabs, meze & baklava',
    phrases: [['Hello','Merhaba'],['Thank you','Teşekkürler'],['Cheers','Şerefe']] },
  'United Kingdom': { lang: 'English',     currency: 'Pound sterling (£)',       dish: 'Fish & chips, Sunday roast',
    phrases: [['Hello','Hello'],['Thank you','Thank you / Ta'],['Cheers','Cheers']] },
  'United States':  { lang: 'English',     currency: 'US dollar ($)',            dish: 'Burgers, BBQ & apple pie',
    phrases: [['Hello','Hello / Hi'],['Thank you','Thank you'],['Cheers','Cheers']] },
  'Mexico':         { lang: 'Spanish',     currency: 'Mexican peso ($/MXN)',     dish: 'Tacos al pastor & mole',
    phrases: [['Hello','Hola'],['Thank you','Gracias'],['Cheers','Salud']] },
  'Indonesia':      { lang: 'Indonesian',  currency: 'Indonesian rupiah (Rp)',   dish: 'Nasi goreng & satay',
    phrases: [['Hello','Halo'],['Thank you','Terima kasih'],['Cheers','Bersulang']] },
  'Micronesia':     { lang: 'English / Pohnpeian', currency: 'US dollar ($)',    dish: 'Reef fish, taro & breadfruit',
    phrases: [['Hello','Kaselehlie'],['Thank you','Kalahngan'],['Cheers','Cheers']] },
  'Bahamas':        { lang: 'English',     currency: 'Bahamian dollar (B$)',     dish: 'Conch fritters & rock lobster',
    phrases: [['Hello','Hello'],['Thank you','Thank you'],['Cheers','Cheers']] },
  'Brazil':         { lang: 'Portuguese',  currency: 'Brazilian real (R$)',      dish: 'Feijoada & pão de queijo',
    phrases: [['Hello','Olá'],['Thank you','Obrigado/a'],['Cheers','Saúde']] },
  'Chile':          { lang: 'Spanish',     currency: 'Chilean peso ($/CLP)',     dish: 'Empanadas & pastel de choclo',
    phrases: [['Hello','Hola'],['Thank you','Gracias'],['Cheers','Salud']] },
  'Peru':           { lang: 'Spanish / Quechua', currency: 'Peruvian sol (S/)',  dish: 'Ceviche & lomo saltado',
    phrases: [['Hello','Hola'],['Thank you','Gracias'],['Cheers','Salud']] },
  /* === world-expansion countries (build_culture.py) — review phrases/dishes === */
  'Japan': { lang: 'Japanese', currency: 'Japanese yen (¥)', dish: 'Sushi, ramen & tempura', phrases: [['Hello','こんにちは'],['Thank you','ありがとう'],['Cheers','乾杯 (Kanpai)']] },
  'China': { lang: 'Mandarin Chinese', currency: 'Chinese yuan (¥)', dish: 'Peking duck & dim sum', phrases: [['Hello','你好 (Nǐ hǎo)'],['Thank you','谢谢 (Xièxie)'],['Cheers','干杯 (Gānbēi)']] },
  'India': { lang: 'Hindi / English', currency: 'Indian rupee (₹)', dish: 'Curry, biryani & dosa', phrases: [['Hello','नमस्ते (Namaste)'],['Thank you','धन्यवाद (Dhanyavaad)'],['Cheers','Cheers']] },
  'South Korea': { lang: 'Korean', currency: 'South Korean won (₩)', dish: 'Kimchi & Korean BBQ', phrases: [['Hello','안녕하세요 (Annyeong)'],['Thank you','감사합니다 (Gamsahamnida)'],['Cheers','건배 (Geonbae)']] },
  'Thailand': { lang: 'Thai', currency: 'Thai baht (฿)', dish: 'Pad Thai & green curry', phrases: [['Hello','สวัสดี (Sawasdee)'],['Thank you','ขอบคุณ (Khop khun)'],['Cheers','ไชโย (Chai-yo)']] },
  'Malaysia': { lang: 'Malay', currency: 'Malaysian ringgit (RM)', dish: 'Nasi lemak & laksa', phrases: [['Hello','Selamat'],['Thank you','Terima kasih'],['Cheers','Cheers']] },
  'Singapore': { lang: 'English / Malay / Mandarin / Tamil', currency: 'Singapore dollar (S$)', dish: 'Chicken rice & chilli crab', phrases: [['Hello','Hello'],['Thank you','Thank you / Terima kasih'],['Cheers','Cheers / Yum seng']] },
  'Philippines': { lang: 'Filipino / English', currency: 'Philippine peso (₱)', dish: 'Adobo & lechon', phrases: [['Hello','Kumusta'],['Thank you','Salamat'],['Cheers','Tagay']] },
  'Vietnam': { lang: 'Vietnamese', currency: 'Vietnamese đồng (₫)', dish: 'Phở & bánh mì', phrases: [['Hello','Xin chào'],['Thank you','Cảm ơn'],['Cheers','Dô / Một hai ba dô']] },
  'Cambodia': { lang: 'Khmer', currency: 'Cambodian riel (៛)', dish: 'Fish amok & lok lak', phrases: [['Hello','Suosdey'],['Thank you','Aw kun'],['Cheers','Chol mouy']] },
  'Laos': { lang: 'Lao', currency: 'Lao kip (₭)', dish: 'Larb & sticky rice', phrases: [['Hello','Sabaidee'],['Thank you','Khob chai'],['Cheers','Sok dee']] },
  'Taiwan': { lang: 'Mandarin Chinese', currency: 'New Taiwan dollar (NT$)', dish: 'Beef noodle soup & bubble tea', phrases: [['Hello','你好 (Nǐ hǎo)'],['Thank you','謝謝 (Xièxie)'],['Cheers','乾杯 (Gānbēi)']] },
  'Mongolia': { lang: 'Mongolian', currency: 'Mongolian tögrög (₮)', dish: 'Buuz dumplings & khorkhog', phrases: [['Hello','Sain baina uu'],['Thank you','Bayarlalaa'],['Cheers','Tuluunii toloo']] },
  'Sri Lanka': { lang: 'Sinhala / Tamil', currency: 'Sri Lankan rupee (Rs)', dish: 'Rice & curry, hoppers', phrases: [['Hello','Ayubowan'],['Thank you','Sthuthi'],['Cheers','Cheers']] },
  'Israel': { lang: 'Hebrew', currency: 'Israeli shekel (₪)', dish: 'Hummus, falafel & shakshuka', phrases: [['Hello','שלום (Shalom)'],['Thank you','תודה (Toda)'],['Cheers','לחיים (L\'chaim)']] },
  'United Arab Emirates': { lang: 'Arabic', currency: 'UAE dirham (د.إ)', dish: 'Shawarma & machboos', phrases: [['Hello','مرحبا (Marhaba)'],['Thank you','شكرا (Shukran)'],['Cheers','بصحتك (Bisaha)']] },
  'Saudi Arabia': { lang: 'Arabic', currency: 'Saudi riyal (ر.س)', dish: 'Kabsa & shawarma', phrases: [['Hello','مرحبا (Marhaba)'],['Thank you','شكرا (Shukran)'],['Cheers','بصحتك (Bisaha)']] },
  'Qatar': { lang: 'Arabic', currency: 'Qatari riyal (ر.ق)', dish: 'Machboos & balaleet', phrases: [['Hello','مرحبا (Marhaba)'],['Thank you','شكرا (Shukran)'],['Cheers','بصحتك (Bisaha)']] },
  'Jordan': { lang: 'Arabic', currency: 'Jordanian dinar (د.ا)', dish: 'Mansaf & falafel', phrases: [['Hello','مرحبا (Marhaba)'],['Thank you','شكرا (Shukran)'],['Cheers','بصحتك (Bisaha)']] },
  'Iran': { lang: 'Persian (Farsi)', currency: 'Iranian rial (﷼)', dish: 'Kebab & ghormeh sabzi', phrases: [['Hello','سلام (Salam)'],['Thank you','ممنون (Mamnoon)'],['Cheers','به سلامتی (Be salamati)']] },
  'Armenia': { lang: 'Armenian', currency: 'Armenian dram (֏)', dish: 'Khorovats & dolma', phrases: [['Hello','Բարև (Barev)'],['Thank you','Շնորհակալություն (Shnorhakalutyun)'],['Cheers','Կենաց (Kenats)']] },
  'Azerbaijan': { lang: 'Azerbaijani', currency: 'Azerbaijani manat (₼)', dish: 'Plov & dolma', phrases: [['Hello','Salam'],['Thank you','Təşəkkür'],['Cheers','Nuş olsun']] },
  'Georgia': { lang: 'Georgian', currency: 'Georgian lari (₾)', dish: 'Khachapuri & khinkali', phrases: [['Hello','გამარჯობა (Gamarjoba)'],['Thank you','მადლობა (Madloba)'],['Cheers','გაუმარჯოს (Gaumarjos)']] },
  'Morocco': { lang: 'Arabic / Berber', currency: 'Moroccan dirham (د.م.)', dish: 'Tagine & couscous', phrases: [['Hello','السلام (Salam)'],['Thank you','شكرا (Shukran)'],['Cheers','بصحتك (Bsaha)']] },
  'Egypt': { lang: 'Arabic', currency: 'Egyptian pound (£)', dish: 'Koshari & ful medames', phrases: [['Hello','السلام عليكم (Salam)'],['Thank you','شكرا (Shukran)'],['Cheers','في صحتك (Fi sahetak)']] },
  'Kenya': { lang: 'Swahili / English', currency: 'Kenyan shilling (KSh)', dish: 'Nyama choma & ugali', phrases: [['Hello','Jambo'],['Thank you','Asante'],['Cheers','Maisha marefu']] },
  'Namibia': { lang: 'English / Oshiwambo / Afrikaans', currency: 'Namibian dollar (N$)', dish: 'Kapana & game biltong', phrases: [['Hello','Hello / Wa lalapo'],['Thank you','Thank you / Tangi'],['Cheers','Cheers']] },
  'Zimbabwe': { lang: 'Shona / Ndebele / English', currency: 'Zimbabwe gold (ZiG) & US dollar', dish: 'Sadza & nyama', phrases: [['Hello','Mhoro'],['Thank you','Ndatenda'],['Cheers','Cheers']] },
  'DR Congo': { lang: 'French / Lingala / Swahili', currency: 'Congolese franc (FC)', dish: 'Fufu & pondu', phrases: [['Hello','Mbote'],['Thank you','Matondo'],['Cheers','Santé']] },
  'North Korea': { lang: 'Korean', currency: 'North Korean won (₩)', dish: 'Pyongyang naengmyŏn (cold noodles)', phrases: [['Hello','안녕하십니까 (Annyŏng hasimnikka)'],['Thank you','감사합니다 (Kamsahamnida)'],['Cheers','축배 (Chukbae)']] },
  'Senegal': { lang: 'French / Wolof', currency: 'West African CFA franc (CFA)', dish: 'Thieboudienne', phrases: [['Hello','Bonjour / Salaam'],['Thank you','Merci / Jërëjëf'],['Cheers','Santé']] },
  'Ethiopia': { lang: 'Amharic', currency: 'Ethiopian birr (Br)', dish: 'Injera & doro wat', phrases: [['Hello','ሰላም (Selam)'],['Thank you','አመሰግናለሁ (Ameseginalehu)'],['Cheers','Bechewanet']] },
  'Gambia': { lang: 'English', currency: 'Gambian dalasi (D)', dish: 'Domoda & benachin', phrases: [['Hello','Hello / Salaam'],['Thank you','Thank you / Jërejëf'],['Cheers','Cheers']] },
  'South Africa': { lang: 'English / Zulu / Afrikaans', currency: 'South African rand (R)', dish: 'Braai & bobotie', phrases: [['Hello','Hello / Sawubona'],['Thank you','Thank you / Ngiyabonga'],['Cheers','Cheers']] },
  'Australia': { lang: 'English', currency: 'Australian dollar (A$)', dish: 'Meat pie, barramundi & Vegemite', phrases: [['Hello','G\'day'],['Thank you','Thanks / Ta'],['Cheers','Cheers']] },
  'New Zealand': { lang: 'English / Māori', currency: 'New Zealand dollar (NZ$)', dish: 'Hāngī & pavlova', phrases: [['Hello','Kia ora'],['Thank you','Ngā mihi'],['Cheers','Cheers']] },
  'Argentina': { lang: 'Spanish', currency: 'Argentine peso ($)', dish: 'Asado & empanadas', phrases: [['Hello','Hola'],['Thank you','Gracias'],['Cheers','Salud']] },
  'Bolivia': { lang: 'Spanish / Quechua / Aymara', currency: 'Bolivian boliviano (Bs)', dish: 'Salteñas & silpancho', phrases: [['Hello','Hola'],['Thank you','Gracias'],['Cheers','Salud']] },
  'Colombia': { lang: 'Spanish', currency: 'Colombian peso ($)', dish: 'Bandeja paisa & arepas', phrases: [['Hello','Hola'],['Thank you','Gracias'],['Cheers','Salud']] },
  'Uruguay': { lang: 'Spanish', currency: 'Uruguayan peso ($U)', dish: 'Asado & chivito', phrases: [['Hello','Hola'],['Thank you','Gracias'],['Cheers','Salud']] },
  'Paraguay': { lang: 'Spanish / Guaraní', currency: 'Paraguayan guaraní (₲)', dish: 'Sopa paraguaya & chipá', phrases: [['Hello','Mba\'éichapa'],['Thank you','Aguyje'],['Cheers','Salud']] },
  'Cuba': { lang: 'Spanish', currency: 'Cuban peso ($)', dish: 'Ropa vieja & moros y cristianos', phrases: [['Hello','Hola'],['Thank you','Gracias'],['Cheers','Salud']] },
  'Costa Rica': { lang: 'Spanish', currency: 'Costa Rican colón (₡)', dish: 'Gallo pinto & casado', phrases: [['Hello','Hola / Pura vida'],['Thank you','Gracias'],['Cheers','Salud']] },
  'Belize': { lang: 'English / Kriol', currency: 'Belize dollar (BZ$)', dish: 'Rice & beans, stew chicken', phrases: [['Hello','Hello'],['Thank you','Thank you'],['Cheers','Cheers']] },
  'Ukraine': { lang: 'Ukrainian', currency: 'Ukrainian hryvnia (₴)', dish: 'Borscht & varenyky', phrases: [['Hello','Привіт (Pryvit)'],['Thank you','Дякую (Diakuyu)'],['Cheers','Будьмо (Budmo)']] },
  'Serbia': { lang: 'Serbian', currency: 'Serbian dinar (дин)', dish: 'Ćevapi & pljeskavica', phrases: [['Hello','Здраво (Zdravo)'],['Thank you','Хвала (Hvala)'],['Cheers','Живели (Živeli)']] },
  'Luxembourg': { lang: 'Luxembourgish / French / German', currency: 'Euro (€)', dish: 'Judd mat Gaardebounen', phrases: [['Hello','Moien'],['Thank you','Merci'],['Cheers','Prost / Santé']] },
  'Lithuania': { lang: 'Lithuanian', currency: 'Euro (€)', dish: 'Cepelinai & šaltibarščiai', phrases: [['Hello','Labas'],['Thank you','Ačiū'],['Cheers','Į sveikatą']] },
  'Latvia': { lang: 'Latvian', currency: 'Euro (€)', dish: 'Grey peas & speck', phrases: [['Hello','Sveiki'],['Thank you','Paldies'],['Cheers','Priekā']] },
  'Moldova': { lang: 'Romanian', currency: 'Moldovan leu (L)', dish: 'Mămăligă & sarmale', phrases: [['Hello','Bună'],['Thank you','Mulțumesc'],['Cheers','Noroc']] },
  'Slovakia': { lang: 'Slovak', currency: 'Euro (€)', dish: 'Bryndzové halušky', phrases: [['Hello','Ahoj'],['Thank you','Ďakujem'],['Cheers','Na zdravie']] },
  'Slovenia': { lang: 'Slovene', currency: 'Euro (€)', dish: 'Potica & štruklji', phrases: [['Hello','Živjo'],['Thank you','Hvala'],['Cheers','Na zdravje']] },
  'Vatican City': { lang: 'Italian / Latin', currency: 'Euro (€)', dish: 'Roman pasta — cacio e pepe', phrases: [['Hello','Buongiorno'],['Thank you','Grazie'],['Cheers','Salute']] },
  'Russia': { lang: 'Russian', currency: 'Russian ruble (₽)', dish: 'Borscht, pelmeni & blini', phrases: [['Hello','Привет (Privet)'],['Thank you','Спасибо (Spasibo)'],['Cheers','На здоровье (Na zdorovie)']] },
  /* === end world-expansion === */

};

/* ISO 3166-1 alpha-2 codes — used to pull local radio by country. */
const COUNTRY_CODES = {
  'Albania':'AL','Austria':'AT','Belgium':'BE','Bosnia and Herzegovina':'BA',
  'Bulgaria':'BG','Canada':'CA','Croatia':'HR','Cyprus':'CY','Czech Republic':'CZ',
  'Denmark':'DK','England':'GB','Estonia':'EE','Faroe Islands':'FO','Finland':'FI',
  'France':'FR','Germany':'DE','Greece':'GR','Hungary':'HU','Iceland':'IS',
  'Ireland':'IE','Italy':'IT','Malta':'MT','Montenegro':'ME','Netherlands':'NL',
  'Norway':'NO','Poland':'PL','Portugal':'PT','Romania':'RO','Spain':'ES',
  'Sweden':'SE','Switzerland':'CH','Turkey':'TR','United Kingdom':'GB','United States':'US',
  'Mexico':'MX','Indonesia':'ID','Micronesia':'FM','Bahamas':'BS','Brazil':'BR',
  'Chile':'CL','Peru':'PE',
  /* === world-expansion countries (build_culture.py) — review phrases/dishes === */
  'Japan':'JP',
  'China':'CN',
  'India':'IN',
  'South Korea':'KR',
  'Thailand':'TH',
  'Malaysia':'MY',
  'Singapore':'SG',
  'Philippines':'PH',
  'Vietnam':'VN',
  'Cambodia':'KH',
  'Laos':'LA',
  'Taiwan':'TW',
  'Mongolia':'MN',
  'Sri Lanka':'LK',
  'Israel':'IL',
  'United Arab Emirates':'AE',
  'Saudi Arabia':'SA',
  'Qatar':'QA',
  'Jordan':'JO',
  'Iran':'IR',
  'Armenia':'AM',
  'Azerbaijan':'AZ',
  'Georgia':'GE',
  'Morocco':'MA',
  'Egypt':'EG',
  'Kenya':'KE',
  'Namibia':'NA',
  'Zimbabwe':'ZW',
  'DR Congo':'CD',
  'North Korea':'KP',
  'Senegal':'SN',
  'Ethiopia':'ET',
  'Gambia':'GM',
  'South Africa':'ZA',
  'Australia':'AU',
  'New Zealand':'NZ',
  'Argentina':'AR',
  'Bolivia':'BO',
  'Colombia':'CO',
  'Uruguay':'UY',
  'Paraguay':'PY',
  'Cuba':'CU',
  'Costa Rica':'CR',
  'Belize':'BZ',
  'Ukraine':'UA',
  'Serbia':'RS',
  'Luxembourg':'LU',
  'Lithuania':'LT',
  'Latvia':'LV',
  'Moldova':'MD',
  'Slovakia':'SK',
  'Slovenia':'SI',
  'Vatican City':'VA',
  'Russia':'RU',
  /* === end world-expansion === */

};

/* ISO 4217 currency codes — used for live exchange rates. */
const CURRENCY_CODES = {
  'Albania':'ALL','Austria':'EUR','Belgium':'EUR','Bosnia and Herzegovina':'BAM',
  'Bulgaria':'BGN','Canada':'CAD','Croatia':'EUR','Cyprus':'EUR','Czech Republic':'CZK',
  'Denmark':'DKK','England':'GBP','Estonia':'EUR','Faroe Islands':'DKK','Finland':'EUR',
  'France':'EUR','Germany':'EUR','Greece':'EUR','Hungary':'HUF','Iceland':'ISK',
  'Ireland':'EUR','Italy':'EUR','Malta':'EUR','Montenegro':'EUR','Netherlands':'EUR',
  'Norway':'NOK','Poland':'PLN','Portugal':'EUR','Romania':'RON','Spain':'EUR',
  'Sweden':'SEK','Switzerland':'CHF','Turkey':'TRY','United Kingdom':'GBP','United States':'USD',
  'Mexico':'MXN','Indonesia':'IDR','Micronesia':'USD','Bahamas':'BSD','Brazil':'BRL',
  'Chile':'CLP','Peru':'PEN',
  /* === world-expansion countries (build_culture.py) — review phrases/dishes === */
  'Japan':'JPY',
  'China':'CNY',
  'India':'INR',
  'South Korea':'KRW',
  'Thailand':'THB',
  'Malaysia':'MYR',
  'Singapore':'SGD',
  'Philippines':'PHP',
  'Vietnam':'VND',
  'Cambodia':'KHR',
  'Laos':'LAK',
  'Taiwan':'TWD',
  'Mongolia':'MNT',
  'Sri Lanka':'LKR',
  'Israel':'ILS',
  'United Arab Emirates':'AED',
  'Saudi Arabia':'SAR',
  'Qatar':'QAR',
  'Jordan':'JOD',
  'Iran':'IRR',
  'Armenia':'AMD',
  'Azerbaijan':'AZN',
  'Georgia':'GEL',
  'Morocco':'MAD',
  'Egypt':'EGP',
  'Kenya':'KES',
  'Namibia':'NAD',
  'Zimbabwe':'ZWL',
  'DR Congo':'CDF',
  'North Korea':'KPW',
  'Senegal':'XOF',
  'Ethiopia':'ETB',
  'Gambia':'GMD',
  'South Africa':'ZAR',
  'Australia':'AUD',
  'New Zealand':'NZD',
  'Argentina':'ARS',
  'Bolivia':'BOB',
  'Colombia':'COP',
  'Uruguay':'UYU',
  'Paraguay':'PYG',
  'Cuba':'CUP',
  'Costa Rica':'CRC',
  'Belize':'BZD',
  'Ukraine':'UAH',
  'Serbia':'RSD',
  'Luxembourg':'EUR',
  'Lithuania':'EUR',
  'Latvia':'EUR',
  'Moldova':'MDL',
  'Slovakia':'EUR',
  'Slovenia':'EUR',
  'Vatican City':'EUR',
  'Russia':'RUB',
  /* === end world-expansion === */

};

/* Quick country facts — capital, rough population, which side they
   drive on, and the plug/voltage you'll need. Hardcoded so it's
   instant and never depends on a flaky API. */
const COUNTRY_FACTS = {
  'Albania':{capital:'Tirana',pop:'2.8M',drives:'Right',plug:'Type C/F · 230V'},
  'Austria':{capital:'Vienna',pop:'9.0M',drives:'Right',plug:'Type C/F · 230V'},
  'Belgium':{capital:'Brussels',pop:'11.7M',drives:'Right',plug:'Type C/E · 230V'},
  'Bosnia and Herzegovina':{capital:'Sarajevo',pop:'3.2M',drives:'Right',plug:'Type C/F · 230V'},
  'Bulgaria':{capital:'Sofia',pop:'6.4M',drives:'Right',plug:'Type C/F · 230V'},
  'Canada':{capital:'Ottawa',pop:'40M',drives:'Right',plug:'Type A/B · 120V'},
  'Croatia':{capital:'Zagreb',pop:'3.9M',drives:'Right',plug:'Type C/F · 230V'},
  'Cyprus':{capital:'Nicosia',pop:'1.2M',drives:'Left',plug:'Type G · 230V'},
  'Czech Republic':{capital:'Prague',pop:'10.5M',drives:'Right',plug:'Type C/E · 230V'},
  'Denmark':{capital:'Copenhagen',pop:'5.9M',drives:'Right',plug:'Type C/E/K · 230V'},
  'England':{capital:'London',pop:'56M',drives:'Left',plug:'Type G · 230V'},
  'Estonia':{capital:'Tallinn',pop:'1.3M',drives:'Right',plug:'Type C/F · 230V'},
  'Faroe Islands':{capital:'Tórshavn',pop:'54K',drives:'Right',plug:'Type C/F/K · 230V'},
  'Finland':{capital:'Helsinki',pop:'5.6M',drives:'Right',plug:'Type C/F · 230V'},
  'France':{capital:'Paris',pop:'68M',drives:'Right',plug:'Type C/E · 230V'},
  'Germany':{capital:'Berlin',pop:'84M',drives:'Right',plug:'Type C/F · 230V'},
  'Greece':{capital:'Athens',pop:'10.4M',drives:'Right',plug:'Type C/F · 230V'},
  'Hungary':{capital:'Budapest',pop:'9.6M',drives:'Right',plug:'Type C/F · 230V'},
  'Iceland':{capital:'Reykjavík',pop:'380K',drives:'Right',plug:'Type C/F · 230V'},
  'Ireland':{capital:'Dublin',pop:'5.1M',drives:'Left',plug:'Type G · 230V'},
  'Italy':{capital:'Rome',pop:'59M',drives:'Right',plug:'Type C/F/L · 230V'},
  'Malta':{capital:'Valletta',pop:'535K',drives:'Left',plug:'Type G · 230V'},
  'Montenegro':{capital:'Podgorica',pop:'620K',drives:'Right',plug:'Type C/F · 230V'},
  'Netherlands':{capital:'Amsterdam',pop:'17.8M',drives:'Right',plug:'Type C/F · 230V'},
  'Norway':{capital:'Oslo',pop:'5.5M',drives:'Right',plug:'Type C/F · 230V'},
  'Poland':{capital:'Warsaw',pop:'37.7M',drives:'Right',plug:'Type C/E · 230V'},
  'Portugal':{capital:'Lisbon',pop:'10.3M',drives:'Right',plug:'Type C/F · 230V'},
  'Romania':{capital:'Bucharest',pop:'19M',drives:'Right',plug:'Type C/F · 230V'},
  'Spain':{capital:'Madrid',pop:'48M',drives:'Right',plug:'Type C/F · 230V'},
  'Sweden':{capital:'Stockholm',pop:'10.5M',drives:'Right',plug:'Type C/F · 230V'},
  'Switzerland':{capital:'Bern',pop:'8.8M',drives:'Right',plug:'Type C/J · 230V'},
  'Turkey':{capital:'Ankara',pop:'85M',drives:'Right',plug:'Type C/F · 230V'},
  'United Kingdom':{capital:'London',pop:'67M',drives:'Left',plug:'Type G · 230V'},
  'United States':{capital:'Washington, D.C.',pop:'335M',drives:'Right',plug:'Type A/B · 120V'},
  'Mexico':{capital:'Mexico City',pop:'129M',drives:'Right',plug:'Type A/B · 127V'},
  'Indonesia':{capital:'Jakarta',pop:'277M',drives:'Left',plug:'Type C/F · 230V'},
  'Micronesia':{capital:'Palikir',pop:'113K',drives:'Right',plug:'Type A/B · 120V'},
  'Bahamas':{capital:'Nassau',pop:'410K',drives:'Left',plug:'Type A/B · 120V'},
  'Brazil':{capital:'Brasília',pop:'216M',drives:'Right',plug:'Type C/N · 127/220V'},
  'Chile':{capital:'Santiago',pop:'19.6M',drives:'Right',plug:'Type C/L · 220V'},
  'Peru':{capital:'Lima',pop:'34M',drives:'Right',plug:'Type A/C · 220V'},
  /* === world-expansion countries (build_culture.py) — review phrases/dishes === */
  'Japan':{capital:'Tokyo',pop:'124M',drives:'Left',plug:'Type A/B · 100V'},
  'China':{capital:'Beijing',pop:'1.41B',drives:'Right',plug:'Type A/I · 220V'},
  'India':{capital:'New Delhi',pop:'1.43B',drives:'Left',plug:'Type C/D/M · 230V'},
  'South Korea':{capital:'Seoul',pop:'52M',drives:'Right',plug:'Type C/F · 220V'},
  'Thailand':{capital:'Bangkok',pop:'72M',drives:'Left',plug:'Type A/B/C · 230V'},
  'Malaysia':{capital:'Kuala Lumpur',pop:'34M',drives:'Left',plug:'Type G · 240V'},
  'Singapore':{capital:'Singapore',pop:'5.9M',drives:'Left',plug:'Type G · 230V'},
  'Philippines':{capital:'Manila',pop:'117M',drives:'Right',plug:'Type A/B/C · 220V'},
  'Vietnam':{capital:'Hanoi',pop:'99M',drives:'Right',plug:'Type A/C · 220V'},
  'Cambodia':{capital:'Phnom Penh',pop:'17M',drives:'Right',plug:'Type A/C/G · 230V'},
  'Laos':{capital:'Vientiane',pop:'7.6M',drives:'Right',plug:'Type A/B/C · 230V'},
  'Taiwan':{capital:'Taipei',pop:'23M',drives:'Right',plug:'Type A/B · 110V'},
  'Mongolia':{capital:'Ulaanbaatar',pop:'3.4M',drives:'Right',plug:'Type C/E · 220V'},
  'Sri Lanka':{capital:'Colombo',pop:'22M',drives:'Left',plug:'Type D/G/M · 230V'},
  'Israel':{capital:'Jerusalem',pop:'9.8M',drives:'Right',plug:'Type C/H · 230V'},
  'United Arab Emirates':{capital:'Abu Dhabi',pop:'9.5M',drives:'Right',plug:'Type G · 230V'},
  'Saudi Arabia':{capital:'Riyadh',pop:'37M',drives:'Right',plug:'Type G · 230V'},
  'Qatar':{capital:'Doha',pop:'2.7M',drives:'Right',plug:'Type D/G · 240V'},
  'Jordan':{capital:'Amman',pop:'11M',drives:'Right',plug:'Type C/D/F/G · 230V'},
  'Iran':{capital:'Tehran',pop:'89M',drives:'Right',plug:'Type C/F · 230V'},
  'Armenia':{capital:'Yerevan',pop:'3.0M',drives:'Right',plug:'Type C/F · 230V'},
  'Azerbaijan':{capital:'Baku',pop:'10M',drives:'Right',plug:'Type C/F · 220V'},
  'Georgia':{capital:'Tbilisi',pop:'3.7M',drives:'Right',plug:'Type C/F · 220V'},
  'Morocco':{capital:'Rabat',pop:'37M',drives:'Right',plug:'Type C/E · 220V'},
  'Egypt':{capital:'Cairo',pop:'113M',drives:'Right',plug:'Type C/F · 220V'},
  'Kenya':{capital:'Nairobi',pop:'55M',drives:'Left',plug:'Type G · 240V'},
  'Namibia':{capital:'Windhoek',pop:'2.6M',drives:'Left',plug:'Type D/M · 220V'},
  'Zimbabwe':{capital:'Harare',pop:'16M',drives:'Left',plug:'Type D/G · 220V'},
  'DR Congo':{capital:'Kinshasa',pop:'102M',drives:'Right',plug:'Type C/D/E · 220V'},
  'North Korea':{capital:'Pyongyang',pop:'26M',drives:'Right',plug:'Type A/C/F · 220V'},
  'Senegal':{capital:'Dakar',pop:'18M',drives:'Right',plug:'Type C/D/E/K · 230V'},
  'Ethiopia':{capital:'Addis Ababa',pop:'127M',drives:'Right',plug:'Type C/F · 220V'},
  'Gambia':{capital:'Banjul',pop:'2.7M',drives:'Right',plug:'Type G · 230V'},
  'South Africa':{capital:'Pretoria',pop:'60M',drives:'Left',plug:'Type M/N · 230V'},
  'Australia':{capital:'Canberra',pop:'26M',drives:'Left',plug:'Type I · 230V'},
  'New Zealand':{capital:'Wellington',pop:'5.2M',drives:'Left',plug:'Type I · 230V'},
  'Argentina':{capital:'Buenos Aires',pop:'46M',drives:'Right',plug:'Type C/I · 220V'},
  'Bolivia':{capital:'Sucre',pop:'12M',drives:'Right',plug:'Type A/C · 230V'},
  'Colombia':{capital:'Bogotá',pop:'52M',drives:'Right',plug:'Type A/B · 110V'},
  'Uruguay':{capital:'Montevideo',pop:'3.4M',drives:'Right',plug:'Type C/F/L · 230V'},
  'Paraguay':{capital:'Asunción',pop:'6.9M',drives:'Right',plug:'Type C · 220V'},
  'Cuba':{capital:'Havana',pop:'11M',drives:'Right',plug:'Type A/B/C · 110/220V'},
  'Costa Rica':{capital:'San José',pop:'5.2M',drives:'Right',plug:'Type A/B · 120V'},
  'Belize':{capital:'Belmopan',pop:'410K',drives:'Right',plug:'Type A/B/G · 110/220V'},
  'Ukraine':{capital:'Kyiv',pop:'38M',drives:'Right',plug:'Type C/F · 230V'},
  'Serbia':{capital:'Belgrade',pop:'6.6M',drives:'Right',plug:'Type C/F · 230V'},
  'Luxembourg':{capital:'Luxembourg City',pop:'660K',drives:'Right',plug:'Type C/F · 230V'},
  'Lithuania':{capital:'Vilnius',pop:'2.9M',drives:'Right',plug:'Type C/F · 230V'},
  'Latvia':{capital:'Riga',pop:'1.9M',drives:'Right',plug:'Type C/F · 230V'},
  'Moldova':{capital:'Chișinău',pop:'2.6M',drives:'Right',plug:'Type C/F · 230V'},
  'Slovakia':{capital:'Bratislava',pop:'5.4M',drives:'Right',plug:'Type C/E · 230V'},
  'Slovenia':{capital:'Ljubljana',pop:'2.1M',drives:'Right',plug:'Type C/F · 230V'},
  'Vatican City':{capital:'Vatican City',pop:'800',drives:'Right',plug:'Type C/F/L · 230V'},
  'Russia':{capital:'Moscow',pop:'144M',drives:'Right',plug:'Type C/F · 230V'},
  /* === end world-expansion === */

};

const Culture = {
  get(country) {
    return COUNTRY_PROFILES[country] || {
      lang: '—', currency: '—', dish: 'Local specialities',
      phrases: [['Hello','Hello'],['Thank you','Thank you'],['Cheers','Cheers']]
    };
  },
  code(country)         { return COUNTRY_CODES[country] || null; },
  currencyCode(country) { return CURRENCY_CODES[country] || null; },
  facts(country)        { return COUNTRY_FACTS[country] || null; }
};

/* ---- WMO weather code → icon + label (day/night aware) ---- */
function weatherInfo(code, isDay = 1) {
  const day = isDay ? 1 : 0;
  const map = {
    0:  [day ? '☀️' : '🌙', day ? 'Clear sky' : 'Clear night'],
    1:  [day ? '🌤️' : '🌙', 'Mainly clear'],
    2:  [day ? '⛅' : '☁️', 'Partly cloudy'],
    3:  ['☁️', 'Overcast'],
    45: ['🌫️', 'Foggy'],  48: ['🌫️', 'Rime fog'],
    51: ['🌦️', 'Light drizzle'], 53: ['🌦️', 'Drizzle'], 55: ['🌦️', 'Heavy drizzle'],
    56: ['🌧️', 'Freezing drizzle'], 57: ['🌧️', 'Freezing drizzle'],
    61: ['🌧️', 'Light rain'], 63: ['🌧️', 'Rain'], 65: ['🌧️', 'Heavy rain'],
    66: ['🌧️', 'Freezing rain'], 67: ['🌧️', 'Freezing rain'],
    71: ['🌨️', 'Light snow'], 73: ['🌨️', 'Snow'], 75: ['❄️', 'Heavy snow'], 77: ['🌨️', 'Snow grains'],
    80: ['🌦️', 'Rain showers'], 81: ['🌦️', 'Rain showers'], 82: ['⛈️', 'Violent showers'],
    85: ['🌨️', 'Snow showers'], 86: ['🌨️', 'Snow showers'],
    95: ['⛈️', 'Thunderstorm'], 96: ['⛈️', 'Storm & hail'], 99: ['⛈️', 'Storm & hail']
  };
  const [icon, label] = map[code] || ['🌍', 'Clear'];
  return { icon, label };
}

export { Culture, weatherInfo };
